// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/capability.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Independent of the server product version. This proposal is protocol 1.1.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_kubling_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_kubling_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// All sizes are uncompressed serialized protobuf bytes unless stated otherwise.
// Zero means unknown, not unlimited. generic_execute_v1 requires positive
// message and batch limits. A client may impose smaller local limits.
type ProtocolLimits struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxRequestMessageBytes  uint64                 `protobuf:"varint,1,opt,name=max_request_message_bytes,json=maxRequestMessageBytes,proto3" json:"max_request_message_bytes,omitempty"`
	MaxResponseMessageBytes uint64                 `protobuf:"varint,2,opt,name=max_response_message_bytes,json=maxResponseMessageBytes,proto3" json:"max_response_message_bytes,omitempty"`
	MaxRowsPerBatch         uint32                 `protobuf:"varint,3,opt,name=max_rows_per_batch,json=maxRowsPerBatch,proto3" json:"max_rows_per_batch,omitempty"`
	MaxBatchBytes           uint64                 `protobuf:"varint,4,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	// Payload bytes per chunk. Required when advertising either LOB feature.
	MaxLobChunkBytes   uint32 `protobuf:"varint,5,opt,name=max_lob_chunk_bytes,json=maxLobChunkBytes,proto3" json:"max_lob_chunk_bytes,omitempty"`
	MaxArrayDimensions uint32 `protobuf:"varint,6,opt,name=max_array_dimensions,json=maxArrayDimensions,proto3" json:"max_array_dimensions,omitempty"`
	// Maximum payload bytes of a newly created LOB; positive with LOB support.
	// Lowering this limit does not invalidate previously issued references.
	MaxLobBytes   uint64 `protobuf:"varint,7,opt,name=max_lob_bytes,json=maxLobBytes,proto3" json:"max_lob_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolLimits) Reset() {
	*x = ProtocolLimits{}
	mi := &file_kubling_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolLimits) ProtoMessage() {}

func (x *ProtocolLimits) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolLimits.ProtoReflect.Descriptor instead.
func (*ProtocolLimits) Descriptor() ([]byte, []int) {
	return file_kubling_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolLimits) GetMaxRequestMessageBytes() uint64 {
	if x != nil {
		return x.MaxRequestMessageBytes
	}
	return 0
}

func (x *ProtocolLimits) GetMaxResponseMessageBytes() uint64 {
	if x != nil {
		return x.MaxResponseMessageBytes
	}
	return 0
}

func (x *ProtocolLimits) GetMaxRowsPerBatch() uint32 {
	if x != nil {
		return x.MaxRowsPerBatch
	}
	return 0
}

func (x *ProtocolLimits) GetMaxBatchBytes() uint64 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *ProtocolLimits) GetMaxLobChunkBytes() uint32 {
	if x != nil {
		return x.MaxLobChunkBytes
	}
	return 0
}

func (x *ProtocolLimits) GetMaxArrayDimensions() uint32 {
	if x != nil {
		return x.MaxArrayDimensions
	}
	return 0
}

func (x *ProtocolLimits) GetMaxLobBytes() uint64 {
	if x != nil {
		return x.MaxLobBytes
	}
	return 0
}

// Logical type support in this session/VDB. Representation features are
// advertised separately; support for BLOB does not imply chunked LOB support.
type SupportedType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ValueType              `protobuf:"varint,1,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	Input         bool                   `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        bool                   `protobuf:"varint,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedType) Reset() {
	*x = SupportedType{}
	mi := &file_kubling_v1_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedType) ProtoMessage() {}

func (x *SupportedType) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedType.ProtoReflect.Descriptor instead.
func (*SupportedType) Descriptor() ([]byte, []int) {
	return file_kubling_v1_capability_proto_rawDescGZIP(), []int{2}
}

func (x *SupportedType) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNKNOWN
}

func (x *SupportedType) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

func (x *SupportedType) GetOutput() bool {
	if x != nil {
		return x.Output
	}
	return false
}

// Effective capabilities for the authenticated session on the serving node.
// Feature names remain in GetServerInfoResponse.features for compatibility.
// A missing message means these guarantees are unavailable.
type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion     *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Limits              *ProtocolLimits        `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	SupportedTypes      []*SupportedType       `protobuf:"bytes,3,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	AffinityRequirement AffinityRequirement    `protobuf:"varint,4,opt,name=affinity_requirement,json=affinityRequirement,proto3,enum=kubling.v1.AffinityRequirement" json:"affinity_requirement,omitempty"`
	Affinity            *Affinity              `protobuf:"bytes,5,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Opaque identity for this snapshot, scoped to the session and serving node.
	// Execute must reject a stale/mismatched identity before executing SQL.
	CapabilityId string `protobuf:"bytes,6,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	// Minimum terminal-outcome retention after completion. Absent means unknown.
	// Does not promise recovery after losing the owning node.
	TransactionStatusRetentionSeconds *uint64 `protobuf:"varint,7,opt,name=transaction_status_retention_seconds,json=transactionStatusRetentionSeconds,proto3,oneof" json:"transaction_status_retention_seconds,omitempty"`
	// Positive minimum lease, measured from reference creation, with LOB support.
	// Every reference carries its own expiry, independent of capability renewal.
	LobReferenceRetentionSeconds *uint64 `protobuf:"varint,8,opt,name=lob_reference_retention_seconds,json=lobReferenceRetentionSeconds,proto3,oneof" json:"lob_reference_retention_seconds,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_kubling_v1_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_kubling_v1_capability_proto_rawDescGZIP(), []int{3}
}

func (x *Capabilities) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *Capabilities) GetLimits() *ProtocolLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Capabilities) GetSupportedTypes() []*SupportedType {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *Capabilities) GetAffinityRequirement() AffinityRequirement {
	if x != nil {
		return x.AffinityRequirement
	}
	return AffinityRequirement_AFFINITY_REQUIREMENT_UNSPECIFIED
}

func (x *Capabilities) GetAffinity() *Affinity {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *Capabilities) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *Capabilities) GetTransactionStatusRetentionSeconds() uint64 {
	if x != nil && x.TransactionStatusRetentionSeconds != nil {
		return *x.TransactionStatusRetentionSeconds
	}
	return 0
}

func (x *Capabilities) GetLobReferenceRetentionSeconds() uint64 {
	if x != nil && x.LobReferenceRetentionSeconds != nil {
		return *x.LobReferenceRetentionSeconds
	}
	return 0
}

var File_kubling_v1_capability_proto protoreflect.FileDescriptor

const file_kubling_v1_capability_proto_rawDesc = "" +
	"\n" +
	"\x1bkubling/v1/capability.proto\x12\n" +
	"kubling.v1\x1a\x1ckubling/v1/transaction.proto\x1a\x16kubling/v1/value.proto\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\xe2\x02\n" +
	"\x0eProtocolLimits\x129\n" +
	"\x19max_request_message_bytes\x18\x01 \x01(\x04R\x16maxRequestMessageBytes\x12;\n" +
	"\x1amax_response_message_bytes\x18\x02 \x01(\x04R\x17maxResponseMessageBytes\x12+\n" +
	"\x12max_rows_per_batch\x18\x03 \x01(\rR\x0fmaxRowsPerBatch\x12&\n" +
	"\x0fmax_batch_bytes\x18\x04 \x01(\x04R\rmaxBatchBytes\x12-\n" +
	"\x13max_lob_chunk_bytes\x18\x05 \x01(\rR\x10maxLobChunkBytes\x120\n" +
	"\x14max_array_dimensions\x18\x06 \x01(\rR\x12maxArrayDimensions\x12\"\n" +
	"\rmax_lob_bytes\x18\a \x01(\x04R\vmaxLobBytes\"h\n" +
	"\rSupportedType\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\x12\x14\n" +
	"\x05input\x18\x02 \x01(\bR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\bR\x06output\"\xe8\x04\n" +
	"\fCapabilities\x12F\n" +
	"\x10protocol_version\x18\x01 \x01(\v2\x1b.kubling.v1.ProtocolVersionR\x0fprotocolVersion\x122\n" +
	"\x06limits\x18\x02 \x01(\v2\x1a.kubling.v1.ProtocolLimitsR\x06limits\x12B\n" +
	"\x0fsupported_types\x18\x03 \x03(\v2\x19.kubling.v1.SupportedTypeR\x0esupportedTypes\x12R\n" +
	"\x14affinity_requirement\x18\x04 \x01(\x0e2\x1f.kubling.v1.AffinityRequirementR\x13affinityRequirement\x120\n" +
	"\baffinity\x18\x05 \x01(\v2\x14.kubling.v1.AffinityR\baffinity\x12#\n" +
	"\rcapability_id\x18\x06 \x01(\tR\fcapabilityId\x12T\n" +
	"$transaction_status_retention_seconds\x18\a \x01(\x04H\x00R!transactionStatusRetentionSeconds\x88\x01\x01\x12J\n" +
	"\x1flob_reference_retention_seconds\x18\b \x01(\x04H\x01R\x1clobReferenceRetentionSeconds\x88\x01\x01B'\n" +
	"%_transaction_status_retention_secondsB\"\n" +
	" _lob_reference_retention_secondsBv\n" +
	"\x1acom.kubling.transport.grpcB\x0fCapabilityProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_capability_proto_rawDescOnce sync.Once
	file_kubling_v1_capability_proto_rawDescData []byte
)

func file_kubling_v1_capability_proto_rawDescGZIP() []byte {
	file_kubling_v1_capability_proto_rawDescOnce.Do(func() {
		file_kubling_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_capability_proto_rawDesc), len(file_kubling_v1_capability_proto_rawDesc)))
	})
	return file_kubling_v1_capability_proto_rawDescData
}

var file_kubling_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubling_v1_capability_proto_goTypes = []any{
	(*ProtocolVersion)(nil),  // 0: kubling.v1.ProtocolVersion
	(*ProtocolLimits)(nil),   // 1: kubling.v1.ProtocolLimits
	(*SupportedType)(nil),    // 2: kubling.v1.SupportedType
	(*Capabilities)(nil),     // 3: kubling.v1.Capabilities
	(ValueType)(0),           // 4: kubling.v1.ValueType
	(AffinityRequirement)(0), // 5: kubling.v1.AffinityRequirement
	(*Affinity)(nil),         // 6: kubling.v1.Affinity
}
var file_kubling_v1_capability_proto_depIdxs = []int32{
	4, // 0: kubling.v1.SupportedType.type:type_name -> kubling.v1.ValueType
	0, // 1: kubling.v1.Capabilities.protocol_version:type_name -> kubling.v1.ProtocolVersion
	1, // 2: kubling.v1.Capabilities.limits:type_name -> kubling.v1.ProtocolLimits
	2, // 3: kubling.v1.Capabilities.supported_types:type_name -> kubling.v1.SupportedType
	5, // 4: kubling.v1.Capabilities.affinity_requirement:type_name -> kubling.v1.AffinityRequirement
	6, // 5: kubling.v1.Capabilities.affinity:type_name -> kubling.v1.Affinity
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kubling_v1_capability_proto_init() }
func file_kubling_v1_capability_proto_init() {
	if File_kubling_v1_capability_proto != nil {
		return
	}
	file_kubling_v1_transaction_proto_init()
	file_kubling_v1_value_proto_init()
	file_kubling_v1_capability_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_capability_proto_rawDesc), len(file_kubling_v1_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_v1_capability_proto_goTypes,
		DependencyIndexes: file_kubling_v1_capability_proto_depIdxs,
		MessageInfos:      file_kubling_v1_capability_proto_msgTypes,
	}.Build()
	File_kubling_v1_capability_proto = out.File
	file_kubling_v1_capability_proto_goTypes = nil
	file_kubling_v1_capability_proto_depIdxs = nil
}
