// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/command.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VdbName         string                 `protobuf:"bytes,1,opt,name=vdb_name,json=vdbName,proto3" json:"vdb_name,omitempty"`
	VdbVersion      string                 `protobuf:"bytes,2,opt,name=vdb_version,json=vdbVersion,proto3" json:"vdb_version,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ApplicationName string                 `protobuf:"bytes,5,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	Properties      map[string]string      `protobuf:"bytes,10,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetVdbName() string {
	if x != nil {
		return x.VdbName
	}
	return ""
}

func (x *LoginRequest) GetVdbVersion() string {
	if x != nil {
		return x.VdbVersion
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *LoginRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	VdbName       string                 `protobuf:"bytes,5,opt,name=vdb_name,json=vdbName,proto3" json:"vdb_name,omitempty"`
	VdbVersion    string                 `protobuf:"bytes,6,opt,name=vdb_version,json=vdbVersion,proto3" json:"vdb_version,omitempty"`
	ClusterName   string                 `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Timezone      string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,10,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetVdbName() string {
	if x != nil {
		return x.VdbName
	}
	return ""
}

func (x *LoginResponse) GetVdbVersion() string {
	if x != nil {
		return x.VdbVersion
	}
	return ""
}

func (x *LoginResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LoginResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *LoginResponse) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SessionPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPingRequest) Reset() {
	*x = SessionPingRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPingRequest) ProtoMessage() {}

func (x *SessionPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPingRequest.ProtoReflect.Descriptor instead.
func (*SessionPingRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{6}
}

func (x *SessionPingRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *SessionPingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPingResponse) Reset() {
	*x = SessionPingResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPingResponse) ProtoMessage() {}

func (x *SessionPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPingResponse.ProtoReflect.Descriptor instead.
func (*SessionPingResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{7}
}

func (x *SessionPingResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Positional SQL parameter.
type Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter value.
	Value         *Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_kubling_v1_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{8}
}

func (x *Parameter) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// SQL execution request.
//
// Intended for:
// - INSERT
// - UPDATE
// - DELETE
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	// SQL statement.
	Sql string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	// Positional SQL parameters.
	Params []*Parameter `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	// buf:lint:ignore FIELD_LOWER_SNAKE_CASE
	ReturnGeneratedKeys bool `protobuf:"varint,4,opt,name=returnGeneratedKeys,proto3" json:"returnGeneratedKeys,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *ExecRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecRequest) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecRequest) GetReturnGeneratedKeys() bool {
	if x != nil {
		return x.ReturnGeneratedKeys
	}
	return false
}

// SQL execution response.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedRows  int64                  `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	UpdateCounts  []int64                `protobuf:"varint,2,rep,packed,name=update_counts,json=updateCounts,proto3" json:"update_counts,omitempty"`
	GeneratedKeys *QueryBatch            `protobuf:"bytes,3,opt,name=generated_keys,json=generatedKeys,proto3,oneof" json:"generated_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetAffectedRows() int64 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

func (x *ExecResponse) GetUpdateCounts() []int64 {
	if x != nil {
		return x.UpdateCounts
	}
	return nil
}

func (x *ExecResponse) GetGeneratedKeys() *QueryBatch {
	if x != nil {
		return x.GeneratedKeys
	}
	return nil
}

// SQL query request.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// SQL query string.
	Sql string `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	// Positional SQL parameters.
	Params []*Parameter `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	// Suggested batch size for streamed results.
	//
	// The server may ignore or adjust this value.
	BatchSize     int32 `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{11}
}

func (x *QueryRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *QueryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// Result column metadata.
type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name.
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType string `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// Indicates whether the column allows null values.
	Nullable      bool  `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Precision     int32 `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         int32 `protobuf:"varint,5,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_kubling_v1_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{12}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Column) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Column) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Column) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// Result row.
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Positional row values.
	Values        []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_kubling_v1_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{13}
}

func (x *Row) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Streamed query batch.
type QueryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned columns metadata.
	//
	// Typically sent in the first batch.
	Columns []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	// Batch rows.
	Rows          []*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatch) Reset() {
	*x = QueryBatch{}
	mi := &file_kubling_v1_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatch) ProtoMessage() {}

func (x *QueryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatch.ProtoReflect.Descriptor instead.
func (*QueryBatch) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{14}
}

func (x *QueryBatch) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryBatch) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Transaction start request.
type BeginTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{15}
}

func (x *BeginTransactionRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

// Transaction start response.
type BeginTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{16}
}

// Transaction commit request.
type CommitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{17}
}

func (x *CommitTransactionRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

// Transaction commit response.
type CommitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionResponse) Reset() {
	*x = CommitTransactionResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionResponse) ProtoMessage() {}

func (x *CommitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionResponse.ProtoReflect.Descriptor instead.
func (*CommitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{18}
}

func (x *CommitTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Transaction rollback request.
type RollbackTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionRequest) Reset() {
	*x = RollbackTransactionRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionRequest) ProtoMessage() {}

func (x *RollbackTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionRequest.ProtoReflect.Descriptor instead.
func (*RollbackTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackTransactionRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

// Transaction rollback response.
type RollbackTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionResponse) Reset() {
	*x = RollbackTransactionResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionResponse) ProtoMessage() {}

func (x *RollbackTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionResponse.ProtoReflect.Descriptor instead.
func (*RollbackTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{20}
}

func (x *RollbackTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IsInTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInTransactionRequest) Reset() {
	*x = IsInTransactionRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInTransactionRequest) ProtoMessage() {}

func (x *IsInTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInTransactionRequest.ProtoReflect.Descriptor instead.
func (*IsInTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{21}
}

func (x *IsInTransactionRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

type IsInTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInTransactionResponse) Reset() {
	*x = IsInTransactionResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInTransactionResponse) ProtoMessage() {}

func (x *IsInTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInTransactionResponse.ProtoReflect.Descriptor instead.
func (*IsInTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{22}
}

func (x *IsInTransactionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Server metadata request.
type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_kubling_v1_command_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{23}
}

// Server metadata response.
type GetServerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubling server version.
	//
	// Example:
	// "26.3.1"
	ServerVersion string `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Supported optional or configured features.
	Features      []string `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_kubling_v1_command_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_command_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_command_proto_rawDescGZIP(), []int{24}
}

func (x *GetServerInfoResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *GetServerInfoResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_kubling_v1_command_proto protoreflect.FileDescriptor

const file_kubling_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x18kubling/v1/command.proto\x12\n" +
	"kubling.v1\x1a\x16kubling/v1/value.proto\"\xb6\x02\n" +
	"\fLoginRequest\x12\x19\n" +
	"\bvdb_name\x18\x01 \x01(\tR\avdbName\x12\x1f\n" +
	"\vvdb_version\x18\x02 \x01(\tR\n" +
	"vdbVersion\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10application_name\x18\x05 \x01(\tR\x0fapplicationName\x12H\n" +
	"\n" +
	"properties\x18\n" +
	" \x03(\v2(.kubling.v1.LoginRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x03\n" +
	"\rLoginResponse\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x19\n" +
	"\bvdb_name\x18\x05 \x01(\tR\avdbName\x12\x1f\n" +
	"\vvdb_version\x18\x06 \x01(\tR\n" +
	"vdbVersion\x12!\n" +
	"\fcluster_name\x18\a \x01(\tR\vclusterName\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12I\n" +
	"\n" +
	"properties\x18\n" +
	" \x03(\v2).kubling.v1.LoginResponse.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\rLogoutRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Z\n" +
	"\x12SessionPingRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"+\n" +
	"\x13SessionPingResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"4\n" +
	"\tParameter\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.kubling.v1.ValueR\x05value\"\xa7\x01\n" +
	"\vExecRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12-\n" +
	"\x06params\x18\x03 \x03(\v2\x15.kubling.v1.ParameterR\x06params\x120\n" +
	"\x13returnGeneratedKeys\x18\x04 \x01(\bR\x13returnGeneratedKeys\"\xaf\x01\n" +
	"\fExecResponse\x12#\n" +
	"\raffected_rows\x18\x01 \x01(\x03R\faffectedRows\x12#\n" +
	"\rupdate_counts\x18\x02 \x03(\x03R\fupdateCounts\x12B\n" +
	"\x0egenerated_keys\x18\x03 \x01(\v2\x16.kubling.v1.QueryBatchH\x00R\rgeneratedKeys\x88\x01\x01B\x11\n" +
	"\x0f_generated_keys\"\xb4\x01\n" +
	"\fQueryRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x12-\n" +
	"\x06params\x18\x04 \x03(\v2\x15.kubling.v1.ParameterR\x06params\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\x05R\tbatchSize\"\x89\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x05 \x01(\x05R\x05scale\"0\n" +
	"\x03Row\x12)\n" +
	"\x06values\x18\x01 \x03(\v2\x11.kubling.v1.ValueR\x06values\"_\n" +
	"\n" +
	"QueryBatch\x12,\n" +
	"\acolumns\x18\x01 \x03(\v2\x12.kubling.v1.ColumnR\acolumns\x12#\n" +
	"\x04rows\x18\x02 \x03(\v2\x0f.kubling.v1.RowR\x04rows\"@\n" +
	"\x17BeginTransactionRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\"\x1a\n" +
	"\x18BeginTransactionResponse\"A\n" +
	"\x18CommitTransactionRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\"5\n" +
	"\x19CommitTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x1aRollbackTransactionRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\"7\n" +
	"\x1bRollbackTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x16IsInTransactionRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\"1\n" +
	"\x17IsInTransactionResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\"\x16\n" +
	"\x14GetServerInfoRequest\"Z\n" +
	"\x15GetServerInfoResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures2\x9a\x02\n" +
	"\x0eSessionService\x12<\n" +
	"\x05Login\x12\x18.kubling.v1.LoginRequest\x1a\x19.kubling.v1.LoginResponse\x12?\n" +
	"\x06Logout\x12\x19.kubling.v1.LogoutRequest\x1a\x1a.kubling.v1.LogoutResponse\x129\n" +
	"\x04Ping\x12\x17.kubling.v1.PingRequest\x1a\x18.kubling.v1.PingResponse\x12N\n" +
	"\vPingSession\x12\x1e.kubling.v1.SessionPingRequest\x1a\x1f.kubling.v1.SessionPingResponse2\xe1\x04\n" +
	"\fQueryService\x129\n" +
	"\x04Exec\x12\x17.kubling.v1.ExecRequest\x1a\x18.kubling.v1.ExecResponse\x12;\n" +
	"\x05Query\x12\x18.kubling.v1.QueryRequest\x1a\x16.kubling.v1.QueryBatch0\x01\x12]\n" +
	"\x10BeginTransaction\x12#.kubling.v1.BeginTransactionRequest\x1a$.kubling.v1.BeginTransactionResponse\x12`\n" +
	"\x11CommitTransaction\x12$.kubling.v1.CommitTransactionRequest\x1a%.kubling.v1.CommitTransactionResponse\x12f\n" +
	"\x13RollbackTransaction\x12&.kubling.v1.RollbackTransactionRequest\x1a'.kubling.v1.RollbackTransactionResponse\x12Z\n" +
	"\x0fIsInTransaction\x12\".kubling.v1.IsInTransactionRequest\x1a#.kubling.v1.IsInTransactionResponse\x12T\n" +
	"\rGetServerInfo\x12 .kubling.v1.GetServerInfoRequest\x1a!.kubling.v1.GetServerInfoResponseBs\n" +
	"\x1acom.kubling.transport.grpcB\fCommandProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1P\x00b\x06proto3"

var (
	file_kubling_v1_command_proto_rawDescOnce sync.Once
	file_kubling_v1_command_proto_rawDescData []byte
)

func file_kubling_v1_command_proto_rawDescGZIP() []byte {
	file_kubling_v1_command_proto_rawDescOnce.Do(func() {
		file_kubling_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_command_proto_rawDesc), len(file_kubling_v1_command_proto_rawDesc)))
	})
	return file_kubling_v1_command_proto_rawDescData
}

var file_kubling_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_kubling_v1_command_proto_goTypes = []any{
	(*LoginRequest)(nil),                // 0: kubling.v1.LoginRequest
	(*LoginResponse)(nil),               // 1: kubling.v1.LoginResponse
	(*LogoutRequest)(nil),               // 2: kubling.v1.LogoutRequest
	(*LogoutResponse)(nil),              // 3: kubling.v1.LogoutResponse
	(*PingRequest)(nil),                 // 4: kubling.v1.PingRequest
	(*PingResponse)(nil),                // 5: kubling.v1.PingResponse
	(*SessionPingRequest)(nil),          // 6: kubling.v1.SessionPingRequest
	(*SessionPingResponse)(nil),         // 7: kubling.v1.SessionPingResponse
	(*Parameter)(nil),                   // 8: kubling.v1.Parameter
	(*ExecRequest)(nil),                 // 9: kubling.v1.ExecRequest
	(*ExecResponse)(nil),                // 10: kubling.v1.ExecResponse
	(*QueryRequest)(nil),                // 11: kubling.v1.QueryRequest
	(*Column)(nil),                      // 12: kubling.v1.Column
	(*Row)(nil),                         // 13: kubling.v1.Row
	(*QueryBatch)(nil),                  // 14: kubling.v1.QueryBatch
	(*BeginTransactionRequest)(nil),     // 15: kubling.v1.BeginTransactionRequest
	(*BeginTransactionResponse)(nil),    // 16: kubling.v1.BeginTransactionResponse
	(*CommitTransactionRequest)(nil),    // 17: kubling.v1.CommitTransactionRequest
	(*CommitTransactionResponse)(nil),   // 18: kubling.v1.CommitTransactionResponse
	(*RollbackTransactionRequest)(nil),  // 19: kubling.v1.RollbackTransactionRequest
	(*RollbackTransactionResponse)(nil), // 20: kubling.v1.RollbackTransactionResponse
	(*IsInTransactionRequest)(nil),      // 21: kubling.v1.IsInTransactionRequest
	(*IsInTransactionResponse)(nil),     // 22: kubling.v1.IsInTransactionResponse
	(*GetServerInfoRequest)(nil),        // 23: kubling.v1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil),       // 24: kubling.v1.GetServerInfoResponse
	nil,                                 // 25: kubling.v1.LoginRequest.PropertiesEntry
	nil,                                 // 26: kubling.v1.LoginResponse.PropertiesEntry
	(*Value)(nil),                       // 27: kubling.v1.Value
}
var file_kubling_v1_command_proto_depIdxs = []int32{
	25, // 0: kubling.v1.LoginRequest.properties:type_name -> kubling.v1.LoginRequest.PropertiesEntry
	26, // 1: kubling.v1.LoginResponse.properties:type_name -> kubling.v1.LoginResponse.PropertiesEntry
	27, // 2: kubling.v1.Parameter.value:type_name -> kubling.v1.Value
	8,  // 3: kubling.v1.ExecRequest.params:type_name -> kubling.v1.Parameter
	14, // 4: kubling.v1.ExecResponse.generated_keys:type_name -> kubling.v1.QueryBatch
	8,  // 5: kubling.v1.QueryRequest.params:type_name -> kubling.v1.Parameter
	27, // 6: kubling.v1.Row.values:type_name -> kubling.v1.Value
	12, // 7: kubling.v1.QueryBatch.columns:type_name -> kubling.v1.Column
	13, // 8: kubling.v1.QueryBatch.rows:type_name -> kubling.v1.Row
	0,  // 9: kubling.v1.SessionService.Login:input_type -> kubling.v1.LoginRequest
	2,  // 10: kubling.v1.SessionService.Logout:input_type -> kubling.v1.LogoutRequest
	4,  // 11: kubling.v1.SessionService.Ping:input_type -> kubling.v1.PingRequest
	6,  // 12: kubling.v1.SessionService.PingSession:input_type -> kubling.v1.SessionPingRequest
	9,  // 13: kubling.v1.QueryService.Exec:input_type -> kubling.v1.ExecRequest
	11, // 14: kubling.v1.QueryService.Query:input_type -> kubling.v1.QueryRequest
	15, // 15: kubling.v1.QueryService.BeginTransaction:input_type -> kubling.v1.BeginTransactionRequest
	17, // 16: kubling.v1.QueryService.CommitTransaction:input_type -> kubling.v1.CommitTransactionRequest
	19, // 17: kubling.v1.QueryService.RollbackTransaction:input_type -> kubling.v1.RollbackTransactionRequest
	21, // 18: kubling.v1.QueryService.IsInTransaction:input_type -> kubling.v1.IsInTransactionRequest
	23, // 19: kubling.v1.QueryService.GetServerInfo:input_type -> kubling.v1.GetServerInfoRequest
	1,  // 20: kubling.v1.SessionService.Login:output_type -> kubling.v1.LoginResponse
	3,  // 21: kubling.v1.SessionService.Logout:output_type -> kubling.v1.LogoutResponse
	5,  // 22: kubling.v1.SessionService.Ping:output_type -> kubling.v1.PingResponse
	7,  // 23: kubling.v1.SessionService.PingSession:output_type -> kubling.v1.SessionPingResponse
	10, // 24: kubling.v1.QueryService.Exec:output_type -> kubling.v1.ExecResponse
	14, // 25: kubling.v1.QueryService.Query:output_type -> kubling.v1.QueryBatch
	16, // 26: kubling.v1.QueryService.BeginTransaction:output_type -> kubling.v1.BeginTransactionResponse
	18, // 27: kubling.v1.QueryService.CommitTransaction:output_type -> kubling.v1.CommitTransactionResponse
	20, // 28: kubling.v1.QueryService.RollbackTransaction:output_type -> kubling.v1.RollbackTransactionResponse
	22, // 29: kubling.v1.QueryService.IsInTransaction:output_type -> kubling.v1.IsInTransactionResponse
	24, // 30: kubling.v1.QueryService.GetServerInfo:output_type -> kubling.v1.GetServerInfoResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kubling_v1_command_proto_init() }
func file_kubling_v1_command_proto_init() {
	if File_kubling_v1_command_proto != nil {
		return
	}
	file_kubling_v1_value_proto_init()
	file_kubling_v1_command_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_command_proto_rawDesc), len(file_kubling_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kubling_v1_command_proto_goTypes,
		DependencyIndexes: file_kubling_v1_command_proto_depIdxs,
		MessageInfos:      file_kubling_v1_command_proto_msgTypes,
	}.Build()
	File_kubling_v1_command_proto = out.File
	file_kubling_v1_command_proto_goTypes = nil
	file_kubling_v1_command_proto_depIdxs = nil
}
