// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/error.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED    ErrorCategory = 0
	ErrorCategory_ERROR_CATEGORY_AUTHENTICATION ErrorCategory = 1
	ErrorCategory_ERROR_CATEGORY_AUTHORIZATION  ErrorCategory = 2
	ErrorCategory_ERROR_CATEGORY_VALIDATION     ErrorCategory = 3
	ErrorCategory_ERROR_CATEGORY_SQL            ErrorCategory = 4
	ErrorCategory_ERROR_CATEGORY_CONSTRAINT     ErrorCategory = 5
	ErrorCategory_ERROR_CATEGORY_UNSUPPORTED    ErrorCategory = 6
	ErrorCategory_ERROR_CATEGORY_RESOURCE       ErrorCategory = 7
	ErrorCategory_ERROR_CATEGORY_TRANSIENT      ErrorCategory = 8
	ErrorCategory_ERROR_CATEGORY_INTERNAL       ErrorCategory = 9
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "ERROR_CATEGORY_AUTHENTICATION",
		2: "ERROR_CATEGORY_AUTHORIZATION",
		3: "ERROR_CATEGORY_VALIDATION",
		4: "ERROR_CATEGORY_SQL",
		5: "ERROR_CATEGORY_CONSTRAINT",
		6: "ERROR_CATEGORY_UNSUPPORTED",
		7: "ERROR_CATEGORY_RESOURCE",
		8: "ERROR_CATEGORY_TRANSIENT",
		9: "ERROR_CATEGORY_INTERNAL",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED":    0,
		"ERROR_CATEGORY_AUTHENTICATION": 1,
		"ERROR_CATEGORY_AUTHORIZATION":  2,
		"ERROR_CATEGORY_VALIDATION":     3,
		"ERROR_CATEGORY_SQL":            4,
		"ERROR_CATEGORY_CONSTRAINT":     5,
		"ERROR_CATEGORY_UNSUPPORTED":    6,
		"ERROR_CATEGORY_RESOURCE":       7,
		"ERROR_CATEGORY_TRANSIENT":      8,
		"ERROR_CATEGORY_INTERNAL":       9,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_kubling_v1_error_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_error_proto_rawDescGZIP(), []int{0}
}

type Retryability int32

const (
	Retryability_RETRYABILITY_UNSPECIFIED Retryability = 0
	Retryability_RETRYABILITY_NEVER       Retryability = 1
	// Server certifies that replay has no duplicate effects. This does not
	// authorize switching SQL RPCs or bypassing the caller's retry policy.
	Retryability_RETRYABILITY_SAFE                     Retryability = 2
	Retryability_RETRYABILITY_RESTART_TRANSACTION      Retryability = 3
	Retryability_RETRYABILITY_CHECK_TRANSACTION_STATUS Retryability = 4
)

// Enum value maps for Retryability.
var (
	Retryability_name = map[int32]string{
		0: "RETRYABILITY_UNSPECIFIED",
		1: "RETRYABILITY_NEVER",
		2: "RETRYABILITY_SAFE",
		3: "RETRYABILITY_RESTART_TRANSACTION",
		4: "RETRYABILITY_CHECK_TRANSACTION_STATUS",
	}
	Retryability_value = map[string]int32{
		"RETRYABILITY_UNSPECIFIED":              0,
		"RETRYABILITY_NEVER":                    1,
		"RETRYABILITY_SAFE":                     2,
		"RETRYABILITY_RESTART_TRANSACTION":      3,
		"RETRYABILITY_CHECK_TRANSACTION_STATUS": 4,
	}
)

func (x Retryability) Enum() *Retryability {
	p := new(Retryability)
	*p = x
	return p
}

func (x Retryability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retryability) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_error_proto_enumTypes[1].Descriptor()
}

func (Retryability) Type() protoreflect.EnumType {
	return &file_kubling_v1_error_proto_enumTypes[1]
}

func (x Retryability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retryability.Descriptor instead.
func (Retryability) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_error_proto_rawDescGZIP(), []int{1}
}

// Pack in google.rpc.Status.details as type.googleapis.com/kubling.v1.KublingError
// and send through grpc-status-details-bin. Never send as an Execute event.
// Human-readable gRPC messages are diagnostic, not machine-readable contracts.
// A transport error may contain no detail; missing/unknown fields never imply
// retry safety or a committed/rolled-back transaction.
type KublingError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required and stable for errors originated/classified by Kubling.
	StableCode string `protobuf:"bytes,1,opt,name=stable_code,json=stableCode,proto3" json:"stable_code,omitempty"`
	// If present, a stable five-character uppercase alphanumeric SQLSTATE.
	SqlState     *string            `protobuf:"bytes,2,opt,name=sql_state,json=sqlState,proto3,oneof" json:"sql_state,omitempty"`
	VendorCode   *int32             `protobuf:"varint,3,opt,name=vendor_code,json=vendorCode,proto3,oneof" json:"vendor_code,omitempty"`
	Category     ErrorCategory      `protobuf:"varint,4,opt,name=category,proto3,enum=kubling.v1.ErrorCategory" json:"category,omitempty"`
	Retryability Retryability       `protobuf:"varint,5,opt,name=retryability,proto3,enum=kubling.v1.Retryability" json:"retryability,omitempty"`
	Transaction  *TransactionStatus `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// False certifies that SQL never started (required on pre-SQL validation
	// errors). True means SQL started, not that it completed or committed.
	// Absent means unknown or not applicable; never infer false from the default.
	SqlExecuted   *bool `protobuf:"varint,7,opt,name=sql_executed,json=sqlExecuted,proto3,oneof" json:"sql_executed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KublingError) Reset() {
	*x = KublingError{}
	mi := &file_kubling_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KublingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KublingError) ProtoMessage() {}

func (x *KublingError) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KublingError.ProtoReflect.Descriptor instead.
func (*KublingError) Descriptor() ([]byte, []int) {
	return file_kubling_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *KublingError) GetStableCode() string {
	if x != nil {
		return x.StableCode
	}
	return ""
}

func (x *KublingError) GetSqlState() string {
	if x != nil && x.SqlState != nil {
		return *x.SqlState
	}
	return ""
}

func (x *KublingError) GetVendorCode() int32 {
	if x != nil && x.VendorCode != nil {
		return *x.VendorCode
	}
	return 0
}

func (x *KublingError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *KublingError) GetRetryability() Retryability {
	if x != nil {
		return x.Retryability
	}
	return Retryability_RETRYABILITY_UNSPECIFIED
}

func (x *KublingError) GetTransaction() *TransactionStatus {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *KublingError) GetSqlExecuted() bool {
	if x != nil && x.SqlExecuted != nil {
		return *x.SqlExecuted
	}
	return false
}

var File_kubling_v1_error_proto protoreflect.FileDescriptor

const file_kubling_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x16kubling/v1/error.proto\x12\n" +
	"kubling.v1\x1a\x1ckubling/v1/transaction.proto\"\x84\x03\n" +
	"\fKublingError\x12\x1f\n" +
	"\vstable_code\x18\x01 \x01(\tR\n" +
	"stableCode\x12 \n" +
	"\tsql_state\x18\x02 \x01(\tH\x00R\bsqlState\x88\x01\x01\x12$\n" +
	"\vvendor_code\x18\x03 \x01(\x05H\x01R\n" +
	"vendorCode\x88\x01\x01\x125\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x19.kubling.v1.ErrorCategoryR\bcategory\x12<\n" +
	"\fretryability\x18\x05 \x01(\x0e2\x18.kubling.v1.RetryabilityR\fretryability\x12?\n" +
	"\vtransaction\x18\x06 \x01(\v2\x1d.kubling.v1.TransactionStatusR\vtransaction\x12&\n" +
	"\fsql_executed\x18\a \x01(\bH\x02R\vsqlExecuted\x88\x01\x01B\f\n" +
	"\n" +
	"_sql_stateB\x0e\n" +
	"\f_vendor_codeB\x0f\n" +
	"\r_sql_executed*\xc2\x02\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dERROR_CATEGORY_AUTHENTICATION\x10\x01\x12 \n" +
	"\x1cERROR_CATEGORY_AUTHORIZATION\x10\x02\x12\x1d\n" +
	"\x19ERROR_CATEGORY_VALIDATION\x10\x03\x12\x16\n" +
	"\x12ERROR_CATEGORY_SQL\x10\x04\x12\x1d\n" +
	"\x19ERROR_CATEGORY_CONSTRAINT\x10\x05\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSUPPORTED\x10\x06\x12\x1b\n" +
	"\x17ERROR_CATEGORY_RESOURCE\x10\a\x12\x1c\n" +
	"\x18ERROR_CATEGORY_TRANSIENT\x10\b\x12\x1b\n" +
	"\x17ERROR_CATEGORY_INTERNAL\x10\t*\xac\x01\n" +
	"\fRetryability\x12\x1c\n" +
	"\x18RETRYABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RETRYABILITY_NEVER\x10\x01\x12\x15\n" +
	"\x11RETRYABILITY_SAFE\x10\x02\x12$\n" +
	" RETRYABILITY_RESTART_TRANSACTION\x10\x03\x12)\n" +
	"%RETRYABILITY_CHECK_TRANSACTION_STATUS\x10\x04Bq\n" +
	"\x1acom.kubling.transport.grpcB\n" +
	"ErrorProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_error_proto_rawDescOnce sync.Once
	file_kubling_v1_error_proto_rawDescData []byte
)

func file_kubling_v1_error_proto_rawDescGZIP() []byte {
	file_kubling_v1_error_proto_rawDescOnce.Do(func() {
		file_kubling_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_error_proto_rawDesc), len(file_kubling_v1_error_proto_rawDesc)))
	})
	return file_kubling_v1_error_proto_rawDescData
}

var file_kubling_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kubling_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kubling_v1_error_proto_goTypes = []any{
	(ErrorCategory)(0),        // 0: kubling.v1.ErrorCategory
	(Retryability)(0),         // 1: kubling.v1.Retryability
	(*KublingError)(nil),      // 2: kubling.v1.KublingError
	(*TransactionStatus)(nil), // 3: kubling.v1.TransactionStatus
}
var file_kubling_v1_error_proto_depIdxs = []int32{
	0, // 0: kubling.v1.KublingError.category:type_name -> kubling.v1.ErrorCategory
	1, // 1: kubling.v1.KublingError.retryability:type_name -> kubling.v1.Retryability
	3, // 2: kubling.v1.KublingError.transaction:type_name -> kubling.v1.TransactionStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kubling_v1_error_proto_init() }
func file_kubling_v1_error_proto_init() {
	if File_kubling_v1_error_proto != nil {
		return
	}
	file_kubling_v1_transaction_proto_init()
	file_kubling_v1_error_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_error_proto_rawDesc), len(file_kubling_v1_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_v1_error_proto_goTypes,
		DependencyIndexes: file_kubling_v1_error_proto_depIdxs,
		EnumInfos:         file_kubling_v1_error_proto_enumTypes,
		MessageInfos:      file_kubling_v1_error_proto_msgTypes,
	}.Build()
	File_kubling_v1_error_proto = out.File
	file_kubling_v1_error_proto_goTypes = nil
	file_kubling_v1_error_proto_depIdxs = nil
}
