// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/lob.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadLobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	LobId         string                 `protobuf:"bytes,2,opt,name=lob_id,json=lobId,proto3" json:"lob_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Absent reads to the end; zero requests an empty range.
	Length *uint64 `protobuf:"varint,4,opt,name=length,proto3,oneof" json:"length,omitempty"`
	// Zero uses the server default; otherwise an upper bound in payload bytes.
	MaxChunkBytes uint32 `protobuf:"varint,5,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
	CapabilityId  string `protobuf:"bytes,6,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLobRequest) Reset() {
	*x = ReadLobRequest{}
	mi := &file_kubling_v1_lob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLobRequest) ProtoMessage() {}

func (x *ReadLobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLobRequest.ProtoReflect.Descriptor instead.
func (*ReadLobRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{0}
}

func (x *ReadLobRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *ReadLobRequest) GetLobId() string {
	if x != nil {
		return x.LobId
	}
	return ""
}

func (x *ReadLobRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadLobRequest) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ReadLobRequest) GetMaxChunkBytes() uint32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

func (x *ReadLobRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

type ReadLobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Exactly the last response marks the requested range complete, including
	// empty ranges. Final gRPC OK is also required for a complete read.
	EndOfRead     bool `protobuf:"varint,3,opt,name=end_of_read,json=endOfRead,proto3" json:"end_of_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLobResponse) Reset() {
	*x = ReadLobResponse{}
	mi := &file_kubling_v1_lob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLobResponse) ProtoMessage() {}

func (x *ReadLobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLobResponse.ProtoReflect.Descriptor instead.
func (*ReadLobResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{1}
}

func (x *ReadLobResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadLobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadLobResponse) GetEndOfRead() bool {
	if x != nil {
		return x.EndOfRead
	}
	return false
}

type WriteLobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*WriteLobRequest_Start
	//	*WriteLobRequest_Chunk
	Part          isWriteLobRequest_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLobRequest) Reset() {
	*x = WriteLobRequest{}
	mi := &file_kubling_v1_lob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLobRequest) ProtoMessage() {}

func (x *WriteLobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLobRequest.ProtoReflect.Descriptor instead.
func (*WriteLobRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{2}
}

func (x *WriteLobRequest) GetPart() isWriteLobRequest_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *WriteLobRequest) GetStart() *LobWriteStart {
	if x != nil {
		if x, ok := x.Part.(*WriteLobRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *WriteLobRequest) GetChunk() *LobChunk {
	if x != nil {
		if x, ok := x.Part.(*WriteLobRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWriteLobRequest_Part interface {
	isWriteLobRequest_Part()
}

type WriteLobRequest_Start struct {
	// Exactly once, first.
	Start *LobWriteStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type WriteLobRequest_Chunk struct {
	// Contiguous offsets starting at zero, after the start message.
	Chunk *LobChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*WriteLobRequest_Start) isWriteLobRequest_Part() {}

func (*WriteLobRequest_Chunk) isWriteLobRequest_Part() {}

type LobWriteStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	// Only BLOB and CLOB are supported. CLOB bytes must form valid UTF-8.
	Type          ValueType `protobuf:"varint,2,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	SizeBytes     *uint64   `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3,oneof" json:"size_bytes,omitempty"`
	CapabilityId  string    `protobuf:"bytes,4,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobWriteStart) Reset() {
	*x = LobWriteStart{}
	mi := &file_kubling_v1_lob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobWriteStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobWriteStart) ProtoMessage() {}

func (x *LobWriteStart) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobWriteStart.ProtoReflect.Descriptor instead.
func (*LobWriteStart) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{3}
}

func (x *LobWriteStart) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *LobWriteStart) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNKNOWN
}

func (x *LobWriteStart) GetSizeBytes() uint64 {
	if x != nil && x.SizeBytes != nil {
		return *x.SizeBytes
	}
	return 0
}

func (x *LobWriteStart) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

type LobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobChunk) Reset() {
	*x = LobChunk{}
	mi := &file_kubling_v1_lob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobChunk) ProtoMessage() {}

func (x *LobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobChunk.ProtoReflect.Descriptor instead.
func (*LobChunk) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{4}
}

func (x *LobChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteLobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Published only after the upload completes and declared size/type validate.
	Reference     *LobReference `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLobResponse) Reset() {
	*x = WriteLobResponse{}
	mi := &file_kubling_v1_lob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLobResponse) ProtoMessage() {}

func (x *WriteLobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLobResponse.ProtoReflect.Descriptor instead.
func (*WriteLobResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{5}
}

func (x *WriteLobResponse) GetReference() *LobReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

type ReleaseLobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiringToken string                 `protobuf:"bytes,1,opt,name=expiring_token,json=expiringToken,proto3" json:"expiring_token,omitempty"`
	LobId         string                 `protobuf:"bytes,2,opt,name=lob_id,json=lobId,proto3" json:"lob_id,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,3,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLobRequest) Reset() {
	*x = ReleaseLobRequest{}
	mi := &file_kubling_v1_lob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLobRequest) ProtoMessage() {}

func (x *ReleaseLobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLobRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLobRequest) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseLobRequest) GetExpiringToken() string {
	if x != nil {
		return x.ExpiringToken
	}
	return ""
}

func (x *ReleaseLobRequest) GetLobId() string {
	if x != nil {
		return x.LobId
	}
	return ""
}

func (x *ReleaseLobRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

type ReleaseLobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLobResponse) Reset() {
	*x = ReleaseLobResponse{}
	mi := &file_kubling_v1_lob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLobResponse) ProtoMessage() {}

func (x *ReleaseLobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_lob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLobResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLobResponse) Descriptor() ([]byte, []int) {
	return file_kubling_v1_lob_proto_rawDescGZIP(), []int{7}
}

var File_kubling_v1_lob_proto protoreflect.FileDescriptor

const file_kubling_v1_lob_proto_rawDesc = "" +
	"\n" +
	"\x14kubling/v1/lob.proto\x12\n" +
	"kubling.v1\x1a\x16kubling/v1/value.proto\"\xdb\x01\n" +
	"\x0eReadLobRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x15\n" +
	"\x06lob_id\x18\x02 \x01(\tR\x05lobId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x1b\n" +
	"\x06length\x18\x04 \x01(\x04H\x00R\x06length\x88\x01\x01\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x05 \x01(\rR\rmaxChunkBytes\x12#\n" +
	"\rcapability_id\x18\x06 \x01(\tR\fcapabilityIdB\t\n" +
	"\a_length\"]\n" +
	"\x0fReadLobResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\vend_of_read\x18\x03 \x01(\bR\tendOfRead\"z\n" +
	"\x0fWriteLobRequest\x121\n" +
	"\x05start\x18\x01 \x01(\v2\x19.kubling.v1.LobWriteStartH\x00R\x05start\x12,\n" +
	"\x05chunk\x18\x02 \x01(\v2\x14.kubling.v1.LobChunkH\x00R\x05chunkB\x06\n" +
	"\x04part\"\xb9\x01\n" +
	"\rLobWriteStart\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\x12\"\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04H\x00R\tsizeBytes\x88\x01\x01\x12#\n" +
	"\rcapability_id\x18\x04 \x01(\tR\fcapabilityIdB\r\n" +
	"\v_size_bytes\"6\n" +
	"\bLobChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"J\n" +
	"\x10WriteLobResponse\x126\n" +
	"\treference\x18\x01 \x01(\v2\x18.kubling.v1.LobReferenceR\treference\"v\n" +
	"\x11ReleaseLobRequest\x12%\n" +
	"\x0eexpiring_token\x18\x01 \x01(\tR\rexpiringToken\x12\x15\n" +
	"\x06lob_id\x18\x02 \x01(\tR\x05lobId\x12#\n" +
	"\rcapability_id\x18\x03 \x01(\tR\fcapabilityId\"\x14\n" +
	"\x12ReleaseLobResponse2\xe8\x01\n" +
	"\n" +
	"LobService\x12D\n" +
	"\aReadLob\x12\x1a.kubling.v1.ReadLobRequest\x1a\x1b.kubling.v1.ReadLobResponse0\x01\x12G\n" +
	"\bWriteLob\x12\x1b.kubling.v1.WriteLobRequest\x1a\x1c.kubling.v1.WriteLobResponse(\x01\x12K\n" +
	"\n" +
	"ReleaseLob\x12\x1d.kubling.v1.ReleaseLobRequest\x1a\x1e.kubling.v1.ReleaseLobResponseBo\n" +
	"\x1acom.kubling.transport.grpcB\bLobProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_lob_proto_rawDescOnce sync.Once
	file_kubling_v1_lob_proto_rawDescData []byte
)

func file_kubling_v1_lob_proto_rawDescGZIP() []byte {
	file_kubling_v1_lob_proto_rawDescOnce.Do(func() {
		file_kubling_v1_lob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_lob_proto_rawDesc), len(file_kubling_v1_lob_proto_rawDesc)))
	})
	return file_kubling_v1_lob_proto_rawDescData
}

var file_kubling_v1_lob_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kubling_v1_lob_proto_goTypes = []any{
	(*ReadLobRequest)(nil),     // 0: kubling.v1.ReadLobRequest
	(*ReadLobResponse)(nil),    // 1: kubling.v1.ReadLobResponse
	(*WriteLobRequest)(nil),    // 2: kubling.v1.WriteLobRequest
	(*LobWriteStart)(nil),      // 3: kubling.v1.LobWriteStart
	(*LobChunk)(nil),           // 4: kubling.v1.LobChunk
	(*WriteLobResponse)(nil),   // 5: kubling.v1.WriteLobResponse
	(*ReleaseLobRequest)(nil),  // 6: kubling.v1.ReleaseLobRequest
	(*ReleaseLobResponse)(nil), // 7: kubling.v1.ReleaseLobResponse
	(ValueType)(0),             // 8: kubling.v1.ValueType
	(*LobReference)(nil),       // 9: kubling.v1.LobReference
}
var file_kubling_v1_lob_proto_depIdxs = []int32{
	3, // 0: kubling.v1.WriteLobRequest.start:type_name -> kubling.v1.LobWriteStart
	4, // 1: kubling.v1.WriteLobRequest.chunk:type_name -> kubling.v1.LobChunk
	8, // 2: kubling.v1.LobWriteStart.type:type_name -> kubling.v1.ValueType
	9, // 3: kubling.v1.WriteLobResponse.reference:type_name -> kubling.v1.LobReference
	0, // 4: kubling.v1.LobService.ReadLob:input_type -> kubling.v1.ReadLobRequest
	2, // 5: kubling.v1.LobService.WriteLob:input_type -> kubling.v1.WriteLobRequest
	6, // 6: kubling.v1.LobService.ReleaseLob:input_type -> kubling.v1.ReleaseLobRequest
	1, // 7: kubling.v1.LobService.ReadLob:output_type -> kubling.v1.ReadLobResponse
	5, // 8: kubling.v1.LobService.WriteLob:output_type -> kubling.v1.WriteLobResponse
	7, // 9: kubling.v1.LobService.ReleaseLob:output_type -> kubling.v1.ReleaseLobResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kubling_v1_lob_proto_init() }
func file_kubling_v1_lob_proto_init() {
	if File_kubling_v1_lob_proto != nil {
		return
	}
	file_kubling_v1_value_proto_init()
	file_kubling_v1_lob_proto_msgTypes[0].OneofWrappers = []any{}
	file_kubling_v1_lob_proto_msgTypes[2].OneofWrappers = []any{
		(*WriteLobRequest_Start)(nil),
		(*WriteLobRequest_Chunk)(nil),
	}
	file_kubling_v1_lob_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_lob_proto_rawDesc), len(file_kubling_v1_lob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubling_v1_lob_proto_goTypes,
		DependencyIndexes: file_kubling_v1_lob_proto_depIdxs,
		MessageInfos:      file_kubling_v1_lob_proto_msgTypes,
	}.Build()
	File_kubling_v1_lob_proto = out.File
	file_kubling_v1_lob_proto_goTypes = nil
	file_kubling_v1_lob_proto_depIdxs = nil
}
