// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kubling/v1/lob.proto

package kublingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LobService_ReadLob_FullMethodName    = "/kubling.v1.LobService/ReadLob"
	LobService_WriteLob_FullMethodName   = "/kubling.v1.LobService/WriteLob"
	LobService_ReleaseLob_FullMethodName = "/kubling.v1.LobService/ReleaseLob"
)

// LobServiceClient is the client API for LobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Optional transfer API, separately gated by lob_read_v1 and lob_write_v1.
// All calls authenticate the owning session and honor its affinity.
// A live reference can use any current compatible capability of that session
// and node, regardless of the snapshot under which the reference was created.
type LobServiceClient interface {
	ReadLob(ctx context.Context, in *ReadLobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadLobResponse], error)
	WriteLob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteLobRequest, WriteLobResponse], error)
	ReleaseLob(ctx context.Context, in *ReleaseLobRequest, opts ...grpc.CallOption) (*ReleaseLobResponse, error)
}

type lobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLobServiceClient(cc grpc.ClientConnInterface) LobServiceClient {
	return &lobServiceClient{cc}
}

func (c *lobServiceClient) ReadLob(ctx context.Context, in *ReadLobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadLobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LobService_ServiceDesc.Streams[0], LobService_ReadLob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadLobRequest, ReadLobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LobService_ReadLobClient = grpc.ServerStreamingClient[ReadLobResponse]

func (c *lobServiceClient) WriteLob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteLobRequest, WriteLobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LobService_ServiceDesc.Streams[1], LobService_WriteLob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteLobRequest, WriteLobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LobService_WriteLobClient = grpc.ClientStreamingClient[WriteLobRequest, WriteLobResponse]

func (c *lobServiceClient) ReleaseLob(ctx context.Context, in *ReleaseLobRequest, opts ...grpc.CallOption) (*ReleaseLobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLobResponse)
	err := c.cc.Invoke(ctx, LobService_ReleaseLob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LobServiceServer is the server API for LobService service.
// All implementations must embed UnimplementedLobServiceServer
// for forward compatibility.
//
// Optional transfer API, separately gated by lob_read_v1 and lob_write_v1.
// All calls authenticate the owning session and honor its affinity.
// A live reference can use any current compatible capability of that session
// and node, regardless of the snapshot under which the reference was created.
type LobServiceServer interface {
	ReadLob(*ReadLobRequest, grpc.ServerStreamingServer[ReadLobResponse]) error
	WriteLob(grpc.ClientStreamingServer[WriteLobRequest, WriteLobResponse]) error
	ReleaseLob(context.Context, *ReleaseLobRequest) (*ReleaseLobResponse, error)
	mustEmbedUnimplementedLobServiceServer()
}

// UnimplementedLobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLobServiceServer struct{}

func (UnimplementedLobServiceServer) ReadLob(*ReadLobRequest, grpc.ServerStreamingServer[ReadLobResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadLob not implemented")
}
func (UnimplementedLobServiceServer) WriteLob(grpc.ClientStreamingServer[WriteLobRequest, WriteLobResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteLob not implemented")
}
func (UnimplementedLobServiceServer) ReleaseLob(context.Context, *ReleaseLobRequest) (*ReleaseLobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLob not implemented")
}
func (UnimplementedLobServiceServer) mustEmbedUnimplementedLobServiceServer() {}
func (UnimplementedLobServiceServer) testEmbeddedByValue()                    {}

// UnsafeLobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LobServiceServer will
// result in compilation errors.
type UnsafeLobServiceServer interface {
	mustEmbedUnimplementedLobServiceServer()
}

func RegisterLobServiceServer(s grpc.ServiceRegistrar, srv LobServiceServer) {
	// If the following call panics, it indicates UnimplementedLobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LobService_ServiceDesc, srv)
}

func _LobService_ReadLob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadLobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LobServiceServer).ReadLob(m, &grpc.GenericServerStream[ReadLobRequest, ReadLobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LobService_ReadLobServer = grpc.ServerStreamingServer[ReadLobResponse]

func _LobService_WriteLob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LobServiceServer).WriteLob(&grpc.GenericServerStream[WriteLobRequest, WriteLobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LobService_WriteLobServer = grpc.ClientStreamingServer[WriteLobRequest, WriteLobResponse]

func _LobService_ReleaseLob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobServiceServer).ReleaseLob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobService_ReleaseLob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobServiceServer).ReleaseLob(ctx, req.(*ReleaseLobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LobService_ServiceDesc is the grpc.ServiceDesc for LobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubling.v1.LobService",
	HandlerType: (*LobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReleaseLob",
			Handler:    _LobService_ReleaseLob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadLob",
			Handler:       _LobService_ReadLob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteLob",
			Handler:       _LobService_WriteLob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "kubling/v1/lob.proto",
}
