// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/transaction.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Required routing scope; UNSPECIFIED must not be interpreted as NONE.
type AffinityRequirement int32

const (
	AffinityRequirement_AFFINITY_REQUIREMENT_UNSPECIFIED      AffinityRequirement = 0
	AffinityRequirement_AFFINITY_REQUIREMENT_NONE             AffinityRequirement = 1
	AffinityRequirement_AFFINITY_REQUIREMENT_SESSION          AffinityRequirement = 2
	AffinityRequirement_AFFINITY_REQUIREMENT_NODE             AffinityRequirement = 3
	AffinityRequirement_AFFINITY_REQUIREMENT_SESSION_AND_NODE AffinityRequirement = 4
)

// Enum value maps for AffinityRequirement.
var (
	AffinityRequirement_name = map[int32]string{
		0: "AFFINITY_REQUIREMENT_UNSPECIFIED",
		1: "AFFINITY_REQUIREMENT_NONE",
		2: "AFFINITY_REQUIREMENT_SESSION",
		3: "AFFINITY_REQUIREMENT_NODE",
		4: "AFFINITY_REQUIREMENT_SESSION_AND_NODE",
	}
	AffinityRequirement_value = map[string]int32{
		"AFFINITY_REQUIREMENT_UNSPECIFIED":      0,
		"AFFINITY_REQUIREMENT_NONE":             1,
		"AFFINITY_REQUIREMENT_SESSION":          2,
		"AFFINITY_REQUIREMENT_NODE":             3,
		"AFFINITY_REQUIREMENT_SESSION_AND_NODE": 4,
	}
)

func (x AffinityRequirement) Enum() *AffinityRequirement {
	p := new(AffinityRequirement)
	*p = x
	return p
}

func (x AffinityRequirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AffinityRequirement) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_transaction_proto_enumTypes[0].Descriptor()
}

func (AffinityRequirement) Type() protoreflect.EnumType {
	return &file_kubling_v1_transaction_proto_enumTypes[0]
}

func (x AffinityRequirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AffinityRequirement.Descriptor instead.
func (AffinityRequirement) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionState int32

const (
	// No authoritative outcome is available. This is not a rollback.
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	TransactionState_TRANSACTION_STATE_UNKNOWN       TransactionState = 0
	TransactionState_TRANSACTION_STATE_NONE          TransactionState = 1
	TransactionState_TRANSACTION_STATE_ACTIVE        TransactionState = 2
	TransactionState_TRANSACTION_STATE_ROLLBACK_ONLY TransactionState = 3
	TransactionState_TRANSACTION_STATE_COMMITTED     TransactionState = 4
	TransactionState_TRANSACTION_STATE_ROLLED_BACK   TransactionState = 5
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNKNOWN",
		1: "TRANSACTION_STATE_NONE",
		2: "TRANSACTION_STATE_ACTIVE",
		3: "TRANSACTION_STATE_ROLLBACK_ONLY",
		4: "TRANSACTION_STATE_COMMITTED",
		5: "TRANSACTION_STATE_ROLLED_BACK",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNKNOWN":       0,
		"TRANSACTION_STATE_NONE":          1,
		"TRANSACTION_STATE_ACTIVE":        2,
		"TRANSACTION_STATE_ROLLBACK_ONLY": 3,
		"TRANSACTION_STATE_COMMITTED":     4,
		"TRANSACTION_STATE_ROLLED_BACK":   5,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_transaction_proto_enumTypes[1].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_kubling_v1_transaction_proto_enumTypes[1]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_transaction_proto_rawDescGZIP(), []int{1}
}

// Routing information, not authentication or authorization. IDs are opaque.
// If supplied, echo routing_token in the "kubling-affinity" request metadata.
// The server must reject a routing mismatch before executing SQL.
type Affinity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoutingToken  string                 `protobuf:"bytes,3,opt,name=routing_token,json=routingToken,proto3" json:"routing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Affinity) Reset() {
	*x = Affinity{}
	mi := &file_kubling_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affinity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affinity) ProtoMessage() {}

func (x *Affinity) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affinity.ProtoReflect.Descriptor instead.
func (*Affinity) Descriptor() ([]byte, []int) {
	return file_kubling_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Affinity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Affinity) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Affinity) GetRoutingToken() string {
	if x != nil {
		return x.RoutingToken
	}
	return ""
}

// An observation at response creation, not a lease or concurrency guarantee.
// NONE requires an empty ID. ACTIVE, ROLLBACK_ONLY, COMMITTED and ROLLED_BACK
// require a non-empty ID. UNKNOWN preserves the queried/affected ID when known;
// an empty UNKNOWN ID is allowed only if no ID was ever issued.
// Unknown/expired lookups return UNKNOWN with the requested ID, not NONE.
type TransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	State         TransactionState       `protobuf:"varint,2,opt,name=state,proto3,enum=kubling.v1.TransactionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatus) Reset() {
	*x = TransactionStatus{}
	mi := &file_kubling_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatus) ProtoMessage() {}

func (x *TransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatus.ProtoReflect.Descriptor instead.
func (*TransactionStatus) Descriptor() ([]byte, []int) {
	return file_kubling_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionStatus) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionStatus) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_TRANSACTION_STATE_UNKNOWN
}

var File_kubling_v1_transaction_proto protoreflect.FileDescriptor

const file_kubling_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1ckubling/v1/transaction.proto\x12\n" +
	"kubling.v1\"g\n" +
	"\bAffinity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rrouting_token\x18\x03 \x01(\tR\froutingToken\"n\n" +
	"\x11TransactionStatus\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.kubling.v1.TransactionStateR\x05state*\xc6\x01\n" +
	"\x13AffinityRequirement\x12$\n" +
	" AFFINITY_REQUIREMENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19AFFINITY_REQUIREMENT_NONE\x10\x01\x12 \n" +
	"\x1cAFFINITY_REQUIREMENT_SESSION\x10\x02\x12\x1d\n" +
	"\x19AFFINITY_REQUIREMENT_NODE\x10\x03\x12)\n" +
	"%AFFINITY_REQUIREMENT_SESSION_AND_NODE\x10\x04*\xd4\x01\n" +
	"\x10TransactionState\x12\x1d\n" +
	"\x19TRANSACTION_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16TRANSACTION_STATE_NONE\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_STATE_ACTIVE\x10\x02\x12#\n" +
	"\x1fTRANSACTION_STATE_ROLLBACK_ONLY\x10\x03\x12\x1f\n" +
	"\x1bTRANSACTION_STATE_COMMITTED\x10\x04\x12!\n" +
	"\x1dTRANSACTION_STATE_ROLLED_BACK\x10\x05Bw\n" +
	"\x1acom.kubling.transport.grpcB\x10TransactionProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_transaction_proto_rawDescOnce sync.Once
	file_kubling_v1_transaction_proto_rawDescData []byte
)

func file_kubling_v1_transaction_proto_rawDescGZIP() []byte {
	file_kubling_v1_transaction_proto_rawDescOnce.Do(func() {
		file_kubling_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_transaction_proto_rawDesc), len(file_kubling_v1_transaction_proto_rawDesc)))
	})
	return file_kubling_v1_transaction_proto_rawDescData
}

var file_kubling_v1_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kubling_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kubling_v1_transaction_proto_goTypes = []any{
	(AffinityRequirement)(0),  // 0: kubling.v1.AffinityRequirement
	(TransactionState)(0),     // 1: kubling.v1.TransactionState
	(*Affinity)(nil),          // 2: kubling.v1.Affinity
	(*TransactionStatus)(nil), // 3: kubling.v1.TransactionStatus
}
var file_kubling_v1_transaction_proto_depIdxs = []int32{
	1, // 0: kubling.v1.TransactionStatus.state:type_name -> kubling.v1.TransactionState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubling_v1_transaction_proto_init() }
func file_kubling_v1_transaction_proto_init() {
	if File_kubling_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_transaction_proto_rawDesc), len(file_kubling_v1_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_v1_transaction_proto_goTypes,
		DependencyIndexes: file_kubling_v1_transaction_proto_depIdxs,
		EnumInfos:         file_kubling_v1_transaction_proto_enumTypes,
		MessageInfos:      file_kubling_v1_transaction_proto_msgTypes,
	}.Build()
	File_kubling_v1_transaction_proto = out.File
	file_kubling_v1_transaction_proto_goTypes = nil
	file_kubling_v1_transaction_proto_depIdxs = nil
}
