// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/value.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical Kubling logical types.
// These values represent logical engine-level semantic types.
type ValueType int32

const (
	// Unspecified type.
	// Preserved for generated-source compatibility.
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	ValueType_VALUE_TYPE_UNKNOWN ValueType = 0
	// Variable-length character string.
	ValueType_VALUE_TYPE_STRING ValueType = 1
	// Variable-length binary value.
	ValueType_VALUE_TYPE_VARBINARY ValueType = 2
	// Single UTF-16 character.
	ValueType_VALUE_TYPE_CHAR ValueType = 3
	// Boolean value.
	ValueType_VALUE_TYPE_BOOLEAN ValueType = 4
	// Signed 8-bit integer.
	ValueType_VALUE_TYPE_BYTE ValueType = 5
	// Signed 16-bit integer.
	ValueType_VALUE_TYPE_SHORT ValueType = 6
	// Signed 32-bit integer.
	ValueType_VALUE_TYPE_INTEGER ValueType = 7
	// Signed 64-bit integer.
	ValueType_VALUE_TYPE_LONG ValueType = 8
	// Arbitrary precision integer.
	ValueType_VALUE_TYPE_BIGINTEGER ValueType = 9
	// 32-bit floating-point number.
	ValueType_VALUE_TYPE_FLOAT ValueType = 10
	// 64-bit floating-point number.
	ValueType_VALUE_TYPE_DOUBLE ValueType = 11
	// Arbitrary precision decimal.
	ValueType_VALUE_TYPE_BIGDECIMAL ValueType = 12
	// Calendar date.
	ValueType_VALUE_TYPE_DATE ValueType = 13
	// Local time.
	ValueType_VALUE_TYPE_TIME ValueType = 14
	// Timestamp with fractional seconds.
	ValueType_VALUE_TYPE_TIMESTAMP ValueType = 15
	// Binary large object.
	ValueType_VALUE_TYPE_BLOB ValueType = 16
	// Character large object.
	ValueType_VALUE_TYPE_CLOB ValueType = 17
	// Geospatial geometry object.
	//
	// Encoded using WKB (Well-Known Binary).
	ValueType_VALUE_TYPE_GEOMETRY ValueType = 18
	// Geospatial geography object.
	//
	// Encoded using WKB (Well-Known Binary).
	ValueType_VALUE_TYPE_GEOGRAPHY ValueType = 19
	// JSON document.
	ValueType_VALUE_TYPE_JSON ValueType = 20
	// XML document.
	ValueType_VALUE_TYPE_XML ValueType = 21
	// Homogeneous array; element type is carried by TypeDescriptor/ArrayValue.
	ValueType_VALUE_TYPE_ARRAY ValueType = 22
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0:  "VALUE_TYPE_UNKNOWN",
		1:  "VALUE_TYPE_STRING",
		2:  "VALUE_TYPE_VARBINARY",
		3:  "VALUE_TYPE_CHAR",
		4:  "VALUE_TYPE_BOOLEAN",
		5:  "VALUE_TYPE_BYTE",
		6:  "VALUE_TYPE_SHORT",
		7:  "VALUE_TYPE_INTEGER",
		8:  "VALUE_TYPE_LONG",
		9:  "VALUE_TYPE_BIGINTEGER",
		10: "VALUE_TYPE_FLOAT",
		11: "VALUE_TYPE_DOUBLE",
		12: "VALUE_TYPE_BIGDECIMAL",
		13: "VALUE_TYPE_DATE",
		14: "VALUE_TYPE_TIME",
		15: "VALUE_TYPE_TIMESTAMP",
		16: "VALUE_TYPE_BLOB",
		17: "VALUE_TYPE_CLOB",
		18: "VALUE_TYPE_GEOMETRY",
		19: "VALUE_TYPE_GEOGRAPHY",
		20: "VALUE_TYPE_JSON",
		21: "VALUE_TYPE_XML",
		22: "VALUE_TYPE_ARRAY",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNKNOWN":    0,
		"VALUE_TYPE_STRING":     1,
		"VALUE_TYPE_VARBINARY":  2,
		"VALUE_TYPE_CHAR":       3,
		"VALUE_TYPE_BOOLEAN":    4,
		"VALUE_TYPE_BYTE":       5,
		"VALUE_TYPE_SHORT":      6,
		"VALUE_TYPE_INTEGER":    7,
		"VALUE_TYPE_LONG":       8,
		"VALUE_TYPE_BIGINTEGER": 9,
		"VALUE_TYPE_FLOAT":      10,
		"VALUE_TYPE_DOUBLE":     11,
		"VALUE_TYPE_BIGDECIMAL": 12,
		"VALUE_TYPE_DATE":       13,
		"VALUE_TYPE_TIME":       14,
		"VALUE_TYPE_TIMESTAMP":  15,
		"VALUE_TYPE_BLOB":       16,
		"VALUE_TYPE_CLOB":       17,
		"VALUE_TYPE_GEOMETRY":   18,
		"VALUE_TYPE_GEOGRAPHY":  19,
		"VALUE_TYPE_JSON":       20,
		"VALUE_TYPE_XML":        21,
		"VALUE_TYPE_ARRAY":      22,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_value_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_kubling_v1_value_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{0}
}

// Portable declared type. Message presence distinguishes inferred from declared
// parameter types. UNKNOWN is not a valid explicitly declared type.
// precision is positive and allowed only for BIGINTEGER/BIGDECIMAL. scale is
// allowed only for BIGDECIMAL, requires precision, and must be <= precision.
// Negative decimal scales are supported. All other types omit both qualifiers.
type TypeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ValueType              `protobuf:"varint,1,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	// Required only for ARRAY. Recursive descriptors describe nested arrays.
	ElementType   *TypeDescriptor `protobuf:"bytes,2,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Precision     *int32          `protobuf:"varint,3,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	Scale         *int32          `protobuf:"varint,4,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDescriptor) Reset() {
	*x = TypeDescriptor{}
	mi := &file_kubling_v1_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDescriptor) ProtoMessage() {}

func (x *TypeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDescriptor.ProtoReflect.Descriptor instead.
func (*TypeDescriptor) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDescriptor) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNKNOWN
}

func (x *TypeDescriptor) GetElementType() *TypeDescriptor {
	if x != nil {
		return x.ElementType
	}
	return nil
}

func (x *TypeDescriptor) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *TypeDescriptor) GetScale() int32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

// Explicit null representation.
type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_kubling_v1_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{1}
}

// Generic typed value.
//
// The selected "kind" field defines the logical Kubling semantic type.
//
// The concrete wire representation may reuse protobuf primitives.
//
// Examples:
// - VALUE_TYPE_BIGDECIMAL -> bigdecimal_value
// - VALUE_TYPE_TIMESTAMP -> timestamp_value
// - VALUE_TYPE_BLOB -> blob_value
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_StringValue
	//	*Value_VarbinaryValue
	//	*Value_CharValue
	//	*Value_BooleanValue
	//	*Value_ByteValue
	//	*Value_ShortValue
	//	*Value_IntegerValue
	//	*Value_LongValue
	//	*Value_BigintegerValue
	//	*Value_FloatValue
	//	*Value_DoubleValue
	//	*Value_BigdecimalValue
	//	*Value_DateValue
	//	*Value_TimeValue
	//	*Value_TimestampValue
	//	*Value_BlobValue
	//	*Value_ClobValue
	//	*Value_XmlValue
	//	*Value_GeometryValue
	//	*Value_GeographyValue
	//	*Value_JsonValue
	//	*Value_ArrayValue
	//	*Value_GeometryWithCrs
	//	*Value_GeographyWithCrs
	//	*Value_LobReference
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_kubling_v1_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNullValue() *NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetVarbinaryValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_VarbinaryValue); ok {
			return x.VarbinaryValue
		}
	}
	return nil
}

func (x *Value) GetCharValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_CharValue); ok {
			return x.CharValue
		}
	}
	return ""
}

func (x *Value) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Value) GetByteValue() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_ByteValue); ok {
			return x.ByteValue
		}
	}
	return 0
}

func (x *Value) GetShortValue() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_ShortValue); ok {
			return x.ShortValue
		}
	}
	return 0
}

func (x *Value) GetIntegerValue() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *Value) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Value) GetBigintegerValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_BigintegerValue); ok {
			return x.BigintegerValue
		}
	}
	return ""
}

func (x *Value) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBigdecimalValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_BigdecimalValue); ok {
			return x.BigdecimalValue
		}
	}
	return ""
}

func (x *Value) GetDateValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *Value) GetTimeValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimeValue); ok {
			return x.TimeValue
		}
	}
	return ""
}

func (x *Value) GetTimestampValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return ""
}

func (x *Value) GetBlobValue() *BlobValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_BlobValue); ok {
			return x.BlobValue
		}
	}
	return nil
}

func (x *Value) GetClobValue() *ClobValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ClobValue); ok {
			return x.ClobValue
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in kubling/v1/value.proto.
func (x *Value) GetXmlValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_XmlValue); ok {
			return x.XmlValue
		}
	}
	return ""
}

func (x *Value) GetGeometryValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_GeometryValue); ok {
			return x.GeometryValue
		}
	}
	return nil
}

func (x *Value) GetGeographyValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_GeographyValue); ok {
			return x.GeographyValue
		}
	}
	return nil
}

func (x *Value) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *Value) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *Value) GetGeometryWithCrs() *SpatialValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_GeometryWithCrs); ok {
			return x.GeometryWithCrs
		}
	}
	return nil
}

func (x *Value) GetGeographyWithCrs() *SpatialValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_GeographyWithCrs); ok {
			return x.GeographyWithCrs
		}
	}
	return nil
}

func (x *Value) GetLobReference() *LobReference {
	if x != nil {
		if x, ok := x.Kind.(*Value_LobReference); ok {
			return x.LobReference
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue *NullValue `protobuf:"bytes,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"` // string / varchar
}

type Value_VarbinaryValue struct {
	VarbinaryValue []byte `protobuf:"bytes,3,opt,name=varbinary_value,json=varbinaryValue,proto3,oneof"` // varbinary
}

type Value_CharValue struct {
	CharValue string `protobuf:"bytes,4,opt,name=char_value,json=charValue,proto3,oneof"` // exactly one Unicode scalar value in the BMP
}

type Value_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,5,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type Value_ByteValue struct {
	ByteValue int32 `protobuf:"varint,6,opt,name=byte_value,json=byteValue,proto3,oneof"` // byte / tinyint, validated -128..127
}

type Value_ShortValue struct {
	ShortValue int32 `protobuf:"varint,7,opt,name=short_value,json=shortValue,proto3,oneof"` // short / smallint, validated -32768..32767
}

type Value_IntegerValue struct {
	IntegerValue int32 `protobuf:"varint,8,opt,name=integer_value,json=integerValue,proto3,oneof"` // integer / serial
}

type Value_LongValue struct {
	LongValue int64 `protobuf:"varint,9,opt,name=long_value,json=longValue,proto3,oneof"` // long / bigint
}

type Value_BigintegerValue struct {
	BigintegerValue string `protobuf:"bytes,10,opt,name=biginteger_value,json=bigintegerValue,proto3,oneof"` // arbitrary precision integer
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,11,opt,name=float_value,json=floatValue,proto3,oneof"` // float / real
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,12,opt,name=double_value,json=doubleValue,proto3,oneof"` // double
}

type Value_BigdecimalValue struct {
	BigdecimalValue string `protobuf:"bytes,13,opt,name=bigdecimal_value,json=bigdecimalValue,proto3,oneof"` // bigdecimal / decimal
}

type Value_DateValue struct {
	DateValue string `protobuf:"bytes,14,opt,name=date_value,json=dateValue,proto3,oneof"` // ISO date: yyyy-MM-dd
}

type Value_TimeValue struct {
	TimeValue string `protobuf:"bytes,15,opt,name=time_value,json=timeValue,proto3,oneof"` // ISO local time: HH:mm:ss[.n]
}

type Value_TimestampValue struct {
	TimestampValue string `protobuf:"bytes,16,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // ISO local timestamp: yyyy-MM-ddTHH:mm:ss[.n]
}

type Value_BlobValue struct {
	BlobValue *BlobValue `protobuf:"bytes,17,opt,name=blob_value,json=blobValue,proto3,oneof"`
}

type Value_ClobValue struct {
	ClobValue *ClobValue `protobuf:"bytes,18,opt,name=clob_value,json=clobValue,proto3,oneof"`
}

type Value_XmlValue struct {
	// Deprecated: Marked as deprecated in kubling/v1/value.proto.
	XmlValue string `protobuf:"bytes,19,opt,name=xml_value,json=xmlValue,proto3,oneof"`
}

type Value_GeometryValue struct {
	GeometryValue []byte `protobuf:"bytes,20,opt,name=geometry_value,json=geometryValue,proto3,oneof"`
}

type Value_GeographyValue struct {
	GeographyValue []byte `protobuf:"bytes,21,opt,name=geography_value,json=geographyValue,proto3,oneof"`
}

type Value_JsonValue struct {
	JsonValue string `protobuf:"bytes,22,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

type Value_ArrayValue struct {
	// Input variants activate their advertised feature by presence; output
	// requires accepted_features. Legacy Query/Exec never emit these variants.
	ArrayValue *ArrayValue `protobuf:"bytes,23,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type Value_GeometryWithCrs struct {
	GeometryWithCrs *SpatialValue `protobuf:"bytes,24,opt,name=geometry_with_crs,json=geometryWithCrs,proto3,oneof"`
}

type Value_GeographyWithCrs struct {
	GeographyWithCrs *SpatialValue `protobuf:"bytes,25,opt,name=geography_with_crs,json=geographyWithCrs,proto3,oneof"`
}

type Value_LobReference struct {
	LobReference *LobReference `protobuf:"bytes,26,opt,name=lob_reference,json=lobReference,proto3,oneof"`
}

func (*Value_NullValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_VarbinaryValue) isValue_Kind() {}

func (*Value_CharValue) isValue_Kind() {}

func (*Value_BooleanValue) isValue_Kind() {}

func (*Value_ByteValue) isValue_Kind() {}

func (*Value_ShortValue) isValue_Kind() {}

func (*Value_IntegerValue) isValue_Kind() {}

func (*Value_LongValue) isValue_Kind() {}

func (*Value_BigintegerValue) isValue_Kind() {}

func (*Value_FloatValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BigdecimalValue) isValue_Kind() {}

func (*Value_DateValue) isValue_Kind() {}

func (*Value_TimeValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_BlobValue) isValue_Kind() {}

func (*Value_ClobValue) isValue_Kind() {}

func (*Value_XmlValue) isValue_Kind() {}

func (*Value_GeometryValue) isValue_Kind() {}

func (*Value_GeographyValue) isValue_Kind() {}

func (*Value_JsonValue) isValue_Kind() {}

func (*Value_ArrayValue) isValue_Kind() {}

func (*Value_GeometryWithCrs) isValue_Kind() {}

func (*Value_GeographyWithCrs) isValue_Kind() {}

func (*Value_LobReference) isValue_Kind() {}

// Empty array is distinct from Value.null_value. Elements may be null, but all
// non-null elements must match element_type. Ragged nested arrays are allowed.
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementType   *TypeDescriptor        `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Elements      []*Value               `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_kubling_v1_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayValue) GetElementType() *TypeDescriptor {
	if x != nil {
		return x.ElementType
	}
	return nil
}

func (x *ArrayValue) GetElements() []*Value {
	if x != nil {
		return x.Elements
	}
	return nil
}

// Plain WKB; no embedded SRID. Missing CRS/SRID means unknown, never EPSG:4326.
// If only SRID is given it denotes an EPSG code. If both are supplied they must
// identify the same CRS. No coordinate transformation is implied.
type SpatialValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Wkb   []byte                 `protobuf:"bytes,1,opt,name=wkb,proto3" json:"wkb,omitempty"`
	Srid  *int32                 `protobuf:"varint,2,opt,name=srid,proto3,oneof" json:"srid,omitempty"`
	// Authority-qualified code (e.g. EPSG:4326) or an absolute CRS URI.
	Crs           *string `protobuf:"bytes,3,opt,name=crs,proto3,oneof" json:"crs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpatialValue) Reset() {
	*x = SpatialValue{}
	mi := &file_kubling_v1_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpatialValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialValue) ProtoMessage() {}

func (x *SpatialValue) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialValue.ProtoReflect.Descriptor instead.
func (*SpatialValue) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{4}
}

func (x *SpatialValue) GetWkb() []byte {
	if x != nil {
		return x.Wkb
	}
	return nil
}

func (x *SpatialValue) GetSrid() int32 {
	if x != nil && x.Srid != nil {
		return *x.Srid
	}
	return 0
}

func (x *SpatialValue) GetCrs() string {
	if x != nil && x.Crs != nil {
		return *x.Crs
	}
	return ""
}

// Immutable, session-scoped BLOB or UTF-8 CLOB, read through LobService.
// References survive statement/transaction closure until expiry, explicit
// release, session closure or node loss. Capability renewal does not invalidate
// them. Resource pressure must reject new creations, never revoke issued leases.
// IDs are opaque and are not bearer credentials.
type LobReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	LobId string                 `protobuf:"bytes,1,opt,name=lob_id,json=lobId,proto3" json:"lob_id,omitempty"`
	Type  ValueType              `protobuf:"varint,2,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	// CLOB sizes and offsets are UTF-8 byte counts, not character counts.
	SizeBytes *uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3,oneof" json:"size_bytes,omitempty"`
	SessionId string  `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Semantically required on every reference issued by Execute or WriteLob.
	ExpiresAtUnixMs *int64 `protobuf:"varint,5,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3,oneof" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LobReference) Reset() {
	*x = LobReference{}
	mi := &file_kubling_v1_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobReference) ProtoMessage() {}

func (x *LobReference) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobReference.ProtoReflect.Descriptor instead.
func (*LobReference) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{5}
}

func (x *LobReference) GetLobId() string {
	if x != nil {
		return x.LobId
	}
	return ""
}

func (x *LobReference) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNKNOWN
}

func (x *LobReference) GetSizeBytes() uint64 {
	if x != nil && x.SizeBytes != nil {
		return *x.SizeBytes
	}
	return 0
}

func (x *LobReference) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LobReference) GetExpiresAtUnixMs() int64 {
	if x != nil && x.ExpiresAtUnixMs != nil {
		return *x.ExpiresAtUnixMs
	}
	return 0
}

type BlobValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobValue) Reset() {
	*x = BlobValue{}
	mi := &file_kubling_v1_value_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobValue) ProtoMessage() {}

func (x *BlobValue) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobValue.ProtoReflect.Descriptor instead.
func (*BlobValue) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{6}
}

func (x *BlobValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClobValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClobValue) Reset() {
	*x = ClobValue{}
	mi := &file_kubling_v1_value_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClobValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClobValue) ProtoMessage() {}

func (x *ClobValue) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_value_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClobValue.ProtoReflect.Descriptor instead.
func (*ClobValue) Descriptor() ([]byte, []int) {
	return file_kubling_v1_value_proto_rawDescGZIP(), []int{7}
}

func (x *ClobValue) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_kubling_v1_value_proto protoreflect.FileDescriptor

const file_kubling_v1_value_proto_rawDesc = "" +
	"\n" +
	"\x16kubling/v1/value.proto\x12\n" +
	"kubling.v1\"\xd0\x01\n" +
	"\x0eTypeDescriptor\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\x12=\n" +
	"\felement_type\x18\x02 \x01(\v2\x1a.kubling.v1.TypeDescriptorR\velementType\x12!\n" +
	"\tprecision\x18\x03 \x01(\x05H\x00R\tprecision\x88\x01\x01\x12\x19\n" +
	"\x05scale\x18\x04 \x01(\x05H\x01R\x05scale\x88\x01\x01B\f\n" +
	"\n" +
	"_precisionB\b\n" +
	"\x06_scale\"\v\n" +
	"\tNullValue\"\x90\t\n" +
	"\x05Value\x126\n" +
	"\n" +
	"null_value\x18\x01 \x01(\v2\x15.kubling.v1.NullValueH\x00R\tnullValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12)\n" +
	"\x0fvarbinary_value\x18\x03 \x01(\fH\x00R\x0evarbinaryValue\x12\x1f\n" +
	"\n" +
	"char_value\x18\x04 \x01(\tH\x00R\tcharValue\x12%\n" +
	"\rboolean_value\x18\x05 \x01(\bH\x00R\fbooleanValue\x12\x1f\n" +
	"\n" +
	"byte_value\x18\x06 \x01(\x05H\x00R\tbyteValue\x12!\n" +
	"\vshort_value\x18\a \x01(\x05H\x00R\n" +
	"shortValue\x12%\n" +
	"\rinteger_value\x18\b \x01(\x05H\x00R\fintegerValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\t \x01(\x03H\x00R\tlongValue\x12+\n" +
	"\x10biginteger_value\x18\n" +
	" \x01(\tH\x00R\x0fbigintegerValue\x12!\n" +
	"\vfloat_value\x18\v \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\f \x01(\x01H\x00R\vdoubleValue\x12+\n" +
	"\x10bigdecimal_value\x18\r \x01(\tH\x00R\x0fbigdecimalValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x0e \x01(\tH\x00R\tdateValue\x12\x1f\n" +
	"\n" +
	"time_value\x18\x0f \x01(\tH\x00R\ttimeValue\x12)\n" +
	"\x0ftimestamp_value\x18\x10 \x01(\tH\x00R\x0etimestampValue\x126\n" +
	"\n" +
	"blob_value\x18\x11 \x01(\v2\x15.kubling.v1.BlobValueH\x00R\tblobValue\x126\n" +
	"\n" +
	"clob_value\x18\x12 \x01(\v2\x15.kubling.v1.ClobValueH\x00R\tclobValue\x12!\n" +
	"\txml_value\x18\x13 \x01(\tB\x02\x18\x01H\x00R\bxmlValue\x12'\n" +
	"\x0egeometry_value\x18\x14 \x01(\fH\x00R\rgeometryValue\x12)\n" +
	"\x0fgeography_value\x18\x15 \x01(\fH\x00R\x0egeographyValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x16 \x01(\tH\x00R\tjsonValue\x129\n" +
	"\varray_value\x18\x17 \x01(\v2\x16.kubling.v1.ArrayValueH\x00R\n" +
	"arrayValue\x12F\n" +
	"\x11geometry_with_crs\x18\x18 \x01(\v2\x18.kubling.v1.SpatialValueH\x00R\x0fgeometryWithCrs\x12H\n" +
	"\x12geography_with_crs\x18\x19 \x01(\v2\x18.kubling.v1.SpatialValueH\x00R\x10geographyWithCrs\x12?\n" +
	"\rlob_reference\x18\x1a \x01(\v2\x18.kubling.v1.LobReferenceH\x00R\flobReferenceB\x06\n" +
	"\x04kind\"z\n" +
	"\n" +
	"ArrayValue\x12=\n" +
	"\felement_type\x18\x01 \x01(\v2\x1a.kubling.v1.TypeDescriptorR\velementType\x12-\n" +
	"\belements\x18\x02 \x03(\v2\x11.kubling.v1.ValueR\belements\"a\n" +
	"\fSpatialValue\x12\x10\n" +
	"\x03wkb\x18\x01 \x01(\fR\x03wkb\x12\x17\n" +
	"\x04srid\x18\x02 \x01(\x05H\x00R\x04srid\x88\x01\x01\x12\x15\n" +
	"\x03crs\x18\x03 \x01(\tH\x01R\x03crs\x88\x01\x01B\a\n" +
	"\x05_sridB\x06\n" +
	"\x04_crs\"\xeb\x01\n" +
	"\fLobReference\x12\x15\n" +
	"\x06lob_id\x18\x01 \x01(\tR\x05lobId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\x12\"\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04H\x00R\tsizeBytes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x120\n" +
	"\x12expires_at_unix_ms\x18\x05 \x01(\x03H\x01R\x0fexpiresAtUnixMs\x88\x01\x01B\r\n" +
	"\v_size_bytesB\x15\n" +
	"\x13_expires_at_unix_ms\"\x1f\n" +
	"\tBlobValue\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1f\n" +
	"\tClobValue\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data*\x9c\x04\n" +
	"\tValueType\x12\x16\n" +
	"\x12VALUE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11VALUE_TYPE_STRING\x10\x01\x12\x18\n" +
	"\x14VALUE_TYPE_VARBINARY\x10\x02\x12\x13\n" +
	"\x0fVALUE_TYPE_CHAR\x10\x03\x12\x16\n" +
	"\x12VALUE_TYPE_BOOLEAN\x10\x04\x12\x13\n" +
	"\x0fVALUE_TYPE_BYTE\x10\x05\x12\x14\n" +
	"\x10VALUE_TYPE_SHORT\x10\x06\x12\x16\n" +
	"\x12VALUE_TYPE_INTEGER\x10\a\x12\x13\n" +
	"\x0fVALUE_TYPE_LONG\x10\b\x12\x19\n" +
	"\x15VALUE_TYPE_BIGINTEGER\x10\t\x12\x14\n" +
	"\x10VALUE_TYPE_FLOAT\x10\n" +
	"\x12\x15\n" +
	"\x11VALUE_TYPE_DOUBLE\x10\v\x12\x19\n" +
	"\x15VALUE_TYPE_BIGDECIMAL\x10\f\x12\x13\n" +
	"\x0fVALUE_TYPE_DATE\x10\r\x12\x13\n" +
	"\x0fVALUE_TYPE_TIME\x10\x0e\x12\x18\n" +
	"\x14VALUE_TYPE_TIMESTAMP\x10\x0f\x12\x13\n" +
	"\x0fVALUE_TYPE_BLOB\x10\x10\x12\x13\n" +
	"\x0fVALUE_TYPE_CLOB\x10\x11\x12\x17\n" +
	"\x13VALUE_TYPE_GEOMETRY\x10\x12\x12\x18\n" +
	"\x14VALUE_TYPE_GEOGRAPHY\x10\x13\x12\x13\n" +
	"\x0fVALUE_TYPE_JSON\x10\x14\x12\x12\n" +
	"\x0eVALUE_TYPE_XML\x10\x15\x12\x14\n" +
	"\x10VALUE_TYPE_ARRAY\x10\x16Bq\n" +
	"\x1acom.kubling.transport.grpcB\n" +
	"ValueProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_value_proto_rawDescOnce sync.Once
	file_kubling_v1_value_proto_rawDescData []byte
)

func file_kubling_v1_value_proto_rawDescGZIP() []byte {
	file_kubling_v1_value_proto_rawDescOnce.Do(func() {
		file_kubling_v1_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_value_proto_rawDesc), len(file_kubling_v1_value_proto_rawDesc)))
	})
	return file_kubling_v1_value_proto_rawDescData
}

var file_kubling_v1_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubling_v1_value_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kubling_v1_value_proto_goTypes = []any{
	(ValueType)(0),         // 0: kubling.v1.ValueType
	(*TypeDescriptor)(nil), // 1: kubling.v1.TypeDescriptor
	(*NullValue)(nil),      // 2: kubling.v1.NullValue
	(*Value)(nil),          // 3: kubling.v1.Value
	(*ArrayValue)(nil),     // 4: kubling.v1.ArrayValue
	(*SpatialValue)(nil),   // 5: kubling.v1.SpatialValue
	(*LobReference)(nil),   // 6: kubling.v1.LobReference
	(*BlobValue)(nil),      // 7: kubling.v1.BlobValue
	(*ClobValue)(nil),      // 8: kubling.v1.ClobValue
}
var file_kubling_v1_value_proto_depIdxs = []int32{
	0,  // 0: kubling.v1.TypeDescriptor.type:type_name -> kubling.v1.ValueType
	1,  // 1: kubling.v1.TypeDescriptor.element_type:type_name -> kubling.v1.TypeDescriptor
	2,  // 2: kubling.v1.Value.null_value:type_name -> kubling.v1.NullValue
	7,  // 3: kubling.v1.Value.blob_value:type_name -> kubling.v1.BlobValue
	8,  // 4: kubling.v1.Value.clob_value:type_name -> kubling.v1.ClobValue
	4,  // 5: kubling.v1.Value.array_value:type_name -> kubling.v1.ArrayValue
	5,  // 6: kubling.v1.Value.geometry_with_crs:type_name -> kubling.v1.SpatialValue
	5,  // 7: kubling.v1.Value.geography_with_crs:type_name -> kubling.v1.SpatialValue
	6,  // 8: kubling.v1.Value.lob_reference:type_name -> kubling.v1.LobReference
	1,  // 9: kubling.v1.ArrayValue.element_type:type_name -> kubling.v1.TypeDescriptor
	3,  // 10: kubling.v1.ArrayValue.elements:type_name -> kubling.v1.Value
	0,  // 11: kubling.v1.LobReference.type:type_name -> kubling.v1.ValueType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kubling_v1_value_proto_init() }
func file_kubling_v1_value_proto_init() {
	if File_kubling_v1_value_proto != nil {
		return
	}
	file_kubling_v1_value_proto_msgTypes[0].OneofWrappers = []any{}
	file_kubling_v1_value_proto_msgTypes[2].OneofWrappers = []any{
		(*Value_NullValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_VarbinaryValue)(nil),
		(*Value_CharValue)(nil),
		(*Value_BooleanValue)(nil),
		(*Value_ByteValue)(nil),
		(*Value_ShortValue)(nil),
		(*Value_IntegerValue)(nil),
		(*Value_LongValue)(nil),
		(*Value_BigintegerValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BigdecimalValue)(nil),
		(*Value_DateValue)(nil),
		(*Value_TimeValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_BlobValue)(nil),
		(*Value_ClobValue)(nil),
		(*Value_XmlValue)(nil),
		(*Value_GeometryValue)(nil),
		(*Value_GeographyValue)(nil),
		(*Value_JsonValue)(nil),
		(*Value_ArrayValue)(nil),
		(*Value_GeometryWithCrs)(nil),
		(*Value_GeographyWithCrs)(nil),
		(*Value_LobReference)(nil),
	}
	file_kubling_v1_value_proto_msgTypes[4].OneofWrappers = []any{}
	file_kubling_v1_value_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_value_proto_rawDesc), len(file_kubling_v1_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_v1_value_proto_goTypes,
		DependencyIndexes: file_kubling_v1_value_proto_depIdxs,
		EnumInfos:         file_kubling_v1_value_proto_enumTypes,
		MessageInfos:      file_kubling_v1_value_proto_msgTypes,
	}.Build()
	File_kubling_v1_value_proto = out.File
	file_kubling_v1_value_proto_goTypes = nil
	file_kubling_v1_value_proto_depIdxs = nil
}
