// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/v1/warning.proto

package kublingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Semantic role of a warning in the terminal execution outcome. Clients use
// this field, never stable_code, message text or list position, to distinguish
// a general diagnostic from an explanation of lost result completeness.
type WarningRole int32

const (
	WarningRole_WARNING_ROLE_UNSPECIFIED          WarningRole = 0
	WarningRole_WARNING_ROLE_GENERAL              WarningRole = 1
	WarningRole_WARNING_ROLE_PARTIAL_RESULT_CAUSE WarningRole = 2
)

// Enum value maps for WarningRole.
var (
	WarningRole_name = map[int32]string{
		0: "WARNING_ROLE_UNSPECIFIED",
		1: "WARNING_ROLE_GENERAL",
		2: "WARNING_ROLE_PARTIAL_RESULT_CAUSE",
	}
	WarningRole_value = map[string]int32{
		"WARNING_ROLE_UNSPECIFIED":          0,
		"WARNING_ROLE_GENERAL":              1,
		"WARNING_ROLE_PARTIAL_RESULT_CAUSE": 2,
	}
)

func (x WarningRole) Enum() *WarningRole {
	p := new(WarningRole)
	*p = x
	return p
}

func (x WarningRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarningRole) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_v1_warning_proto_enumTypes[0].Descriptor()
}

func (WarningRole) Type() protoreflect.EnumType {
	return &file_kubling_v1_warning_proto_enumTypes[0]
}

func (x WarningRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarningRole.Descriptor instead.
func (WarningRole) EnumDescriptor() ([]byte, []int) {
	return file_kubling_v1_warning_proto_rawDescGZIP(), []int{0}
}

// Optional logical location for an execution warning. Every identifier must be
// safe for the authenticated caller. Do not expose credentials, physical
// endpoints, internal URLs or other source-private details.
type WarningContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      *uint64                `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3,oneof" json:"result_id,omitempty"`
	ModelId       *string                `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3,oneof" json:"model_id,omitempty"`
	SourceId      *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarningContext) Reset() {
	*x = WarningContext{}
	mi := &file_kubling_v1_warning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarningContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarningContext) ProtoMessage() {}

func (x *WarningContext) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_warning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarningContext.ProtoReflect.Descriptor instead.
func (*WarningContext) Descriptor() ([]byte, []int) {
	return file_kubling_v1_warning_proto_rawDescGZIP(), []int{0}
}

func (x *WarningContext) GetResultId() uint64 {
	if x != nil && x.ResultId != nil {
		return *x.ResultId
	}
	return 0
}

func (x *WarningContext) GetModelId() string {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return ""
}

func (x *WarningContext) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

// Structured diagnostic attached to a successful Execute terminal event.
// Completeness decisions come from ExecutionEnd.completeness and causal
// classification comes from role. Warning order has no semantic meaning.
type KublingWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required, non-empty and stable for warnings classified by Kubling.
	StableCode string `protobuf:"bytes,1,opt,name=stable_code,json=stableCode,proto3" json:"stable_code,omitempty"`
	// Required human-readable diagnostic. It must be sanitized and is not stable.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// When present, a five-character uppercase alphanumeric SQLSTATE.
	SqlState *string `protobuf:"bytes,3,opt,name=sql_state,json=sqlState,proto3,oneof" json:"sql_state,omitempty"`
	// Presence distinguishes an absent code from an explicitly reported zero.
	VendorCode *int32          `protobuf:"varint,4,opt,name=vendor_code,json=vendorCode,proto3,oneof" json:"vendor_code,omitempty"`
	Context    *WarningContext `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	// Positive number of occurrences represented by this warning.
	OccurrenceCount uint64 `protobuf:"varint,6,opt,name=occurrence_count,json=occurrenceCount,proto3" json:"occurrence_count,omitempty"`
	// Bounded, authorized logical resource identifiers represented by this warning.
	AffectedResourceIds []string `protobuf:"bytes,7,rep,name=affected_resource_ids,json=affectedResourceIds,proto3" json:"affected_resource_ids,omitempty"`
	// Additional affected resource IDs omitted from this warning.
	OmittedAffectedResourceIdCount uint64 `protobuf:"varint,8,opt,name=omitted_affected_resource_id_count,json=omittedAffectedResourceIdCount,proto3" json:"omitted_affected_resource_id_count,omitempty"`
	// Required to be GENERAL or PARTIAL_RESULT_CAUSE when partial_results_v1 is
	// accepted. Stable codes never substitute for this classification.
	Role          WarningRole `protobuf:"varint,9,opt,name=role,proto3,enum=kubling.v1.WarningRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KublingWarning) Reset() {
	*x = KublingWarning{}
	mi := &file_kubling_v1_warning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KublingWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KublingWarning) ProtoMessage() {}

func (x *KublingWarning) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_v1_warning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KublingWarning.ProtoReflect.Descriptor instead.
func (*KublingWarning) Descriptor() ([]byte, []int) {
	return file_kubling_v1_warning_proto_rawDescGZIP(), []int{1}
}

func (x *KublingWarning) GetStableCode() string {
	if x != nil {
		return x.StableCode
	}
	return ""
}

func (x *KublingWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KublingWarning) GetSqlState() string {
	if x != nil && x.SqlState != nil {
		return *x.SqlState
	}
	return ""
}

func (x *KublingWarning) GetVendorCode() int32 {
	if x != nil && x.VendorCode != nil {
		return *x.VendorCode
	}
	return 0
}

func (x *KublingWarning) GetContext() *WarningContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *KublingWarning) GetOccurrenceCount() uint64 {
	if x != nil {
		return x.OccurrenceCount
	}
	return 0
}

func (x *KublingWarning) GetAffectedResourceIds() []string {
	if x != nil {
		return x.AffectedResourceIds
	}
	return nil
}

func (x *KublingWarning) GetOmittedAffectedResourceIdCount() uint64 {
	if x != nil {
		return x.OmittedAffectedResourceIdCount
	}
	return 0
}

func (x *KublingWarning) GetRole() WarningRole {
	if x != nil {
		return x.Role
	}
	return WarningRole_WARNING_ROLE_UNSPECIFIED
}

var File_kubling_v1_warning_proto protoreflect.FileDescriptor

const file_kubling_v1_warning_proto_rawDesc = "" +
	"\n" +
	"\x18kubling/v1/warning.proto\x12\n" +
	"kubling.v1\"\x9d\x01\n" +
	"\x0eWarningContext\x12 \n" +
	"\tresult_id\x18\x01 \x01(\x04H\x00R\bresultId\x88\x01\x01\x12\x1e\n" +
	"\bmodel_id\x18\x02 \x01(\tH\x01R\amodelId\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x02R\bsourceId\x88\x01\x01B\f\n" +
	"\n" +
	"_result_idB\v\n" +
	"\t_model_idB\f\n" +
	"\n" +
	"_source_id\"\xbf\x03\n" +
	"\x0eKublingWarning\x12\x1f\n" +
	"\vstable_code\x18\x01 \x01(\tR\n" +
	"stableCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\tsql_state\x18\x03 \x01(\tH\x00R\bsqlState\x88\x01\x01\x12$\n" +
	"\vvendor_code\x18\x04 \x01(\x05H\x01R\n" +
	"vendorCode\x88\x01\x01\x124\n" +
	"\acontext\x18\x05 \x01(\v2\x1a.kubling.v1.WarningContextR\acontext\x12)\n" +
	"\x10occurrence_count\x18\x06 \x01(\x04R\x0foccurrenceCount\x122\n" +
	"\x15affected_resource_ids\x18\a \x03(\tR\x13affectedResourceIds\x12J\n" +
	"\"omitted_affected_resource_id_count\x18\b \x01(\x04R\x1eomittedAffectedResourceIdCount\x12+\n" +
	"\x04role\x18\t \x01(\x0e2\x17.kubling.v1.WarningRoleR\x04roleB\f\n" +
	"\n" +
	"_sql_stateB\x0e\n" +
	"\f_vendor_code*l\n" +
	"\vWarningRole\x12\x1c\n" +
	"\x18WARNING_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14WARNING_ROLE_GENERAL\x10\x01\x12%\n" +
	"!WARNING_ROLE_PARTIAL_RESULT_CAUSE\x10\x02Bs\n" +
	"\x1acom.kubling.transport.grpcB\fWarningProtoP\x01ZEgithub.com/kubling-community/kubling-grpc/sdk-go/kubling/v1;kublingv1b\x06proto3"

var (
	file_kubling_v1_warning_proto_rawDescOnce sync.Once
	file_kubling_v1_warning_proto_rawDescData []byte
)

func file_kubling_v1_warning_proto_rawDescGZIP() []byte {
	file_kubling_v1_warning_proto_rawDescOnce.Do(func() {
		file_kubling_v1_warning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_v1_warning_proto_rawDesc), len(file_kubling_v1_warning_proto_rawDesc)))
	})
	return file_kubling_v1_warning_proto_rawDescData
}

var file_kubling_v1_warning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubling_v1_warning_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kubling_v1_warning_proto_goTypes = []any{
	(WarningRole)(0),       // 0: kubling.v1.WarningRole
	(*WarningContext)(nil), // 1: kubling.v1.WarningContext
	(*KublingWarning)(nil), // 2: kubling.v1.KublingWarning
}
var file_kubling_v1_warning_proto_depIdxs = []int32{
	1, // 0: kubling.v1.KublingWarning.context:type_name -> kubling.v1.WarningContext
	0, // 1: kubling.v1.KublingWarning.role:type_name -> kubling.v1.WarningRole
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kubling_v1_warning_proto_init() }
func file_kubling_v1_warning_proto_init() {
	if File_kubling_v1_warning_proto != nil {
		return
	}
	file_kubling_v1_warning_proto_msgTypes[0].OneofWrappers = []any{}
	file_kubling_v1_warning_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_v1_warning_proto_rawDesc), len(file_kubling_v1_warning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_v1_warning_proto_goTypes,
		DependencyIndexes: file_kubling_v1_warning_proto_depIdxs,
		EnumInfos:         file_kubling_v1_warning_proto_enumTypes,
		MessageInfos:      file_kubling_v1_warning_proto_msgTypes,
	}.Build()
	File_kubling_v1_warning_proto = out.File
	file_kubling_v1_warning_proto_goTypes = nil
	file_kubling_v1_warning_proto_depIdxs = nil
}
