// Code generated by tools/generate_features.py. DO NOT EDIT.

pub const GENERIC_EXECUTE_V1: &str = "generic_execute_v1";
pub const TYPED_PARAMETERS_V1: &str = "typed_parameters_v1";
pub const STRUCTURED_ERRORS_V1: &str = "structured_errors_v1";
pub const TRANSACTION_IDS_V1: &str = "transaction_ids_v1";
pub const TRANSACTION_STATUS_V1: &str = "transaction_status_v1";
pub const ARRAY_VALUES_V1: &str = "array_values_v1";
pub const SPATIAL_VALUES_V1: &str = "spatial_values_v1";
pub const LOB_READ_V1: &str = "lob_read_v1";
pub const LOB_WRITE_V1: &str = "lob_write_v1";
pub const MULTIPLE_RESULTS_V1: &str = "multiple_results_v1";
pub const GENERATED_KEYS_V1: &str = "generated_keys_v1";
