#!/usr/bin/env python3
"""Generate feature constants for all clients from the canonical registry."""

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def validate_expression(expression, response=False):
    if expression is None:
        return
    if not isinstance(expression, dict):
        raise ValueError("Activation expression must be an object or null")
    keys = set(expression)
    if keys in ({"any_of"}, {"all_of"}):
        children = expression[next(iter(keys))]
        if not isinstance(children, list) or len(children) < 2 or any(c is None for c in children):
            raise ValueError("Activation groups require at least two non-null expressions")
        for child in children:
            validate_expression(child, response)
    elif keys == {"rpc"}:
        if not isinstance(expression["rpc"], str) or not re.fullmatch(r"/kubling\.v1\.[A-Za-z][A-Za-z0-9]*/[A-Za-z][A-Za-z0-9]*", expression["rpc"]):
            raise ValueError("Invalid activation RPC")
    elif keys == {"field", "test"}:
        if not isinstance(expression["field"], str) or not re.fullmatch(r"kubling\.v1\.[A-Za-z][A-Za-z0-9]*\.[a-z][a-z0-9_]*", expression["field"]):
            raise ValueError("Invalid activation field")
        if expression["test"] not in ("present", "nonempty", "true"):
            raise ValueError("Unknown activation predicate")
    elif keys == {"accepted_features"}:
        if expression["accepted_features"] is not True:
            raise ValueError("accepted_features must be true")
    elif keys == {"advertised"}:
        if not response or expression["advertised"] is not True:
            raise ValueError("advertised is a response-only true predicate")
    else:
        raise ValueError("Unknown or ambiguous activation expression")


def validate_registry(registry):
    if not isinstance(registry, dict) or set(registry) != {"schema_version", "features"} or type(registry["schema_version"]) is not int or registry["schema_version"] != 2:
        raise ValueError("Expected feature registry schema_version 2")
    features = registry["features"]
    if not isinstance(features, list) or not features:
        raise ValueError("Expected a nonempty feature list")
    for feature in features:
        if not isinstance(feature, dict) or set(feature) != {"name", "symbol", "requires", "description", "activation"}:
            raise ValueError("Invalid feature fields")
        for key in ("name", "symbol", "description"):
            if not isinstance(feature[key], str) or not feature[key].strip():
                raise ValueError("Feature text must be nonempty")
        requires = feature["requires"]
        if not isinstance(requires, list) or not all(isinstance(r, str) for r in requires) or len(set(requires)) != len(requires):
            raise ValueError("Invalid or duplicate feature dependencies")
        activation = feature["activation"]
        if not isinstance(activation, dict) or set(activation) != {"request", "response", "request_requires_acceptance"}:
            raise ValueError("Invalid activation fields")
        if type(activation["request_requires_acceptance"]) is not bool:
            raise ValueError("request_requires_acceptance must be boolean")
        if activation["request"] is None and (activation["response"] is None or activation["request_requires_acceptance"]):
            raise ValueError("Feature requires an activation path")
        validate_expression(activation["request"])
        validate_expression(activation["response"], response=True)
    names = {f["name"] for f in features}
    symbols = {f["symbol"] for f in features}
    if len(names) != len(features) or len(symbols) != len(features):
        raise ValueError("Duplicate feature name or symbol")
    for feature in features:
        if not re.fullmatch(r"[a-z][a-z0-9_]*_v[1-9][0-9]*", feature["name"]):
            raise ValueError("Invalid feature name")
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", feature["symbol"]):
            raise ValueError("Invalid feature symbol")
        if not set(feature["requires"]) <= names:
            raise ValueError("Unknown feature dependency")
    dependencies = {f["name"]: f["requires"] for f in features}

    def visit(name, pending):
        if name in pending:
            raise ValueError("Cyclic feature dependency")
        for dependency in dependencies[name]:
            visit(dependency, pending | {name})

    for name in names:
        visit(name, set())
    return features


def outputs():
    features = validate_registry(json.loads((ROOT / "protocol/features.json").read_text()))
    notice = "Code generated by tools/generate_features.py. DO NOT EDIT."
    go = "// " + notice + "\n\npackage features\n\nconst (\n"
    width = max(len(f["symbol"]) for f in features)
    for feature in features:
        go += "\t" + feature["symbol"].ljust(width) + ' = "' + feature["name"] + '"\n'
    go += ")\n"
    python = "# " + notice + "\n\n"
    rust = "// " + notice + "\n\n"
    java = ("// " + notice + "\n\npackage com.kubling.transport.grpc;\n\n"
            "public final class Features {\n    private Features() {}\n\n")
    for feature in features:
        symbol, name = feature["name"].upper(), feature["name"]
        python += f'{symbol} = "{name}"\n'
        rust += f'pub const {symbol}: &str = "{name}";\n'
        java += f'    public static final String {symbol} = "{name}";\n'
    java += "}\n"
    return {
        "sdk-go/features/features.go": go,
        "sdk-python/generated/kubling/features.py": python,
        "sdk-rust/features/features.rs": rust,
        "sdk-java/generated/com/kubling/transport/grpc/Features.java": java,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--language", choices=("all", "go", "java", "python", "rust"), default="all")
    args = parser.parse_args()
    stale = []
    for relative, content in outputs().items():
        if args.language != "all" and not relative.startswith(f"sdk-{args.language}/"):
            continue
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Outdated feature constants: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
