// Code generated by tools/generate_features.py. DO NOT EDIT.

package features

const (
	GenericExecuteV1    = "generic_execute_v1"
	TypedParametersV1   = "typed_parameters_v1"
	StructuredErrorsV1  = "structured_errors_v1"
	TransactionIdsV1    = "transaction_ids_v1"
	TransactionStatusV1 = "transaction_status_v1"
	ArrayValuesV1       = "array_values_v1"
	SpatialValuesV1     = "spatial_values_v1"
	LobReadV1           = "lob_read_v1"
	LobWriteV1          = "lob_write_v1"
	MultipleResultsV1   = "multiple_results_v1"
	GeneratedKeysV1     = "generated_keys_v1"
)
