name: Protobuf

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.lock'
      - '.github/workflows/proto.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.lock'
      - '.github/workflows/proto.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    name: Validate and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Validate and publish protobuf module
        uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
